const $=id=>document.getElementById(id);
const labels={kalshi:'Kalshi',polymarket_us:'Polymarket US',the_odds_api:'The Odds API',novig:'Novig',prophetx:'ProphetX'};
const value=x=>x===null||x===undefined?'Unknown':typeof x==='object'?JSON.stringify(x):String(x);
const seconds=x=>x===null||x===undefined?'Unknown':`${Math.round(x)}s`;
const name=x=>labels[x]||x;
const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=value(text);return e;};
function pairs(target,rows){const dl=node('dl');for(const [key,v] of rows){dl.append(node('dt',key),node('dd',v));}target.replaceChildren(dl);}
function replaceIfChanged(target,build,key){if(target.dataset.key===key)return;target.dataset.key=key;build();}
let current=null,busy=false,pulling=false,pollGeneration=0;
function render(s){
  current=s;
  if(s.evidence_class&&!$('synthetic-notice')){const notice=node('p',s.evidence_class);notice.id='synthetic-notice';document.querySelector('h1').after(notice);}
  pairs($('service'),[['State',s.service_state||s.state],['Acquisition owner',s.ownership_held?'Held by this runtime':'Not held by this runtime'],['Runtime / attempt',`${value(s.runtime_id)} / ${value(s.attempt_id)}`],['Candidate',s.candidate_digest],['Attended deadline',seconds(s.deadline_remaining_seconds)],['Board attendance',s.attendance?'Board connected':'Open a board to attend'],['Cleanup',s.cleanup_complete?'Complete':s.cleanup_errors?.length?s.cleanup_errors.join(', '):'Pending until stop'],['Recovery gate',s.recovery?.reason||'Ready for guarded replacement']]);
  for(const b of document.querySelectorAll('[data-action]'))b.disabled=busy||(b.dataset.action==='recover'&&(!s.recovery||!!s.recovery.reason));
  const panels=s.sources||[];
  // Stable source controls and open disclosures survive polling.
  for(const p of panels){
    let card=$('source-'+p.provider);
    if(!card){card=node('section');card.id='source-'+p.provider;card.append(node('h2',name(p.provider)),node('p','Affects '+p.affected_venues.map(name).join(' and ')));const body=node('div');body.className='source-body';card.append(body);const button=node('button','Pause '+(p.provider==='the_odds_api'?'both aggregate venues':name(p.provider)));button.dataset.action='pause';button.dataset.source=p.provider;card.append(button);$('sources').append(card);}
    pairs(card.querySelector('.source-body'),[['Availability',Object.entries(p.status).map(([v,x])=>`${name(v)}: ${x.state} — ${x.reason}`).join('\n')],['Last book / receipt',`${value(p.last_book_observation_at)} / ${value(p.last_book_receipt_at)}`],['Retained price source time',p.source_at],['Source age / meaning',`${seconds(p.source_age_seconds)} / ${p.timestamp_meanings.join(', ')||'Unknown'}`],['Last price receipt',p.received_at],['Receipt age',seconds(p.receipt_age_seconds)],['Retained prices',p.quotes],['Verified / eligible',`${p.identity_verified} identity verified / ${p.comparison_eligible} comparison eligible / ${p.stale} stale`],['Discovery / subscription',`${value(p.metrics.generations)} generations / ${value(p.metrics.selected_markets)} selected markets`],['Connections / requests',`${value(p.metrics.connections)} / ${value(p.metrics.requests)}`],['Reconnect / backoff',`${value(p.metrics.retries)} retries / ${seconds(p.backoff_remaining_seconds)} remaining`],['Calculation eligibility',Object.entries(p.calculation_eligible||{}).map(([k,n])=>`${k.replaceAll('_',' ')}: ${n}`).join(' / ')],['Next action',p.next_action||(p.worker_done?'Worker ended. Inspect issues and cleanup before guarded recovery.':p.provider==='the_odds_api'?'Wait for attendance, evidenced quota and the persisted due slot.':'Wait for source images within the bounded runtime.')],['Freshness policy',p.freshness_policies.length?p.freshness_policies.map(x=>`${x.version}: ${x.maximum_age_seconds}s engineering threshold`).join('; '):'No evidenced freshness policy for retained prices']]);
  }
  for(const b of document.querySelectorAll('[data-action="pause"]'))b.disabled=busy||!s.dispatch_enabled;
  const q=s.quota;
  pairs($('quota'),q?[['Monthly ceiling / reserve',`${q.ceiling} / ${q.engineering_reserve} credits`],['Provider used / remaining',`${value(q.used)} / ${value(q.remaining)}`],['Usage observed at',q.observation?.at],['Observation age',seconds(q.observation_age_seconds)],['Unresolved reservations',`${value(q.reserved)} credits / ${value(q.unresolved_attempts)} attempts`],['Conservative allowance',`${value(q.available)} credits above reserve; out-of-band spend may reduce this`],['Evidenced reset window',q.reset?`${q.reset.starts_at} → ${q.reset.ends_at}`:'Unknown — dispatch blocked'],['Next batch / bootstrap due',`${value(q.next_due_at)} / ${value(q.bootstrap_due_at)}`],['Sport rotation',`${value(q.rotation)} / ${panels.find(x=>x.provider==='the_odds_api')?.active_sports?.join(', ')||'Not discovered in this runtime'}`],['Dispatch gate',q.pause||panels.find(x=>x.provider==='the_odds_api')?.status.novig?.reason||'Unknown']]:[['Accounting','No shared scheduler configured; no provider balance verified.']]);
  const issues=s.issues||[];
  replaceIfChanged($('issues'),()=>{const children=issues.map(i=>{const wrap=node('article');wrap.className='issue';wrap.append(node('h3',`${name(i.provider)} · ${i.kind.replaceAll('_',' ')}`));const body=node('div');wrap.append(body);pairs(body,[['Affects',i.affected_venues.map(name).join(', ')],['Impact',i.impact],['Next action',i.next_action],['First / last observation',`${i.first_at} / ${i.last_at} (${i.occurrences} occurrences)`],['Scope / endpoint class',`${i.scope.sports.join(', ')} · ${i.scope.families.join(', ')} / ${i.endpoint_class.replaceAll('_',' ')}`],['Healthy independent paths',i.healthy_independent_paths.map(name).join(', ')||'None observed at issue time'],['Charge / reserved',`${value(i.credits)} / ${value(i.reserved_credits)} credits`],['Retry / backoff',`${i.retry_count} retries / ${i.backoff_seconds.join(', ')||'No automatic retry'} seconds`],['Runtime / attempt / candidate',`${i.runtime_id} / ${i.attempt_id} / ${i.candidate_digest}`]]);return wrap;});$('issues').replaceChildren(...(children.length?children:[node('p','No issues recorded in this runtime. This does not establish fresh quotes or provider coverage.')]));},JSON.stringify(issues));
  replaceIfChanged($('historical'),()=>{for(const i of s.historical_issues||[]){const wrap=node('article');pairs(wrap,[['Historical observation',i.observed_at],['Scope',i.scope],['Impact',i.impact],['Next action',i.next_action],['Paid batch charge',i.credits],['Candidate / attempt',`${i.candidate_digest} / ${i.attempt_id}`]]);const a=node('a','Retained U4 issue provenance');a.href='/api/admin/u4-issue';wrap.append(a);$('historical').replaceChildren(wrap);}},JSON.stringify(s.historical_issues));
  replaceIfChanged($('exclusions'),()=>{const x=s.exclusions||[];$('exclusions').replaceChildren(node('p',x.length?`${x.length} current admission exclusions`:'No sink exclusions recorded. Source discovery exclusions remain in technical measurements.'),...x.slice(0,100).map(e=>node('p',`${name(e.source)} · ${e.market_id} — ${e.reason}`)));},JSON.stringify(s.exclusions));
  const r=s.resources||{};
  pairs($('measurements'),[['RSS sampled / sampled high-water / ceiling',`${value(r.sampled_rss_bytes)} / ${value(r.sampled_highwater_rss_bytes)} / ${value(r.rss_ceiling_bytes)} bytes`],['Encoded state / ceiling',`${value(r.state_encoded_bytes)} / ${value(r.state_ceiling_bytes)} bytes`],['Issue buffer / bounds',`${value(r.issue_records)} records, ${value(r.issue_encoded_bytes)} bytes / ${value(r.issue_record_ceiling)} records, ${value(r.issue_byte_ceiling)} bytes`],['Streams / pending notices / held reviews',`${value(r.subscribers)} / ${value(r.pending_notices)} / ${value(r.reviews)}`],['Admitted / rejected observations',`${value(s.sink?.admitted_observations)} / ${value(s.sink?.rejected_observations)}`],['Retained records / identity exclusions',`${value(s.sink?.admitted_records)} / ${value(s.sink?.identity_excluded_records)}`],['Commit latency last / high-water',`${value(s.sink?.last_commit_ms)} / ${value(s.sink?.max_commit_ms)} ms`],['Latency meaning','source_receipt_ms is a source-clock age difference; receipt_projection_ms is local image processing. http_response_ms measures awaited HTTP delivery. No browser paint latency is measured.']]);
  $('technical').textContent=JSON.stringify(s,null,2);
}
async function refresh(){if(pulling||busy)return;pulling=true;const generation=pollGeneration;try{const response=await fetch('/api/admin/status');if(!response.ok)throw Error();const data=await response.json();if(generation===pollGeneration&&!busy)render(data);}catch{if(generation!==pollGeneration||busy)return;$('feedback').textContent='Admin status unavailable. Controls require a current status response.';current=null;for(const b of document.querySelectorAll('[data-action]'))b.disabled=true;}finally{pulling=false;}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||busy)return;busy=true;pollGeneration++;for(const x of document.querySelectorAll('[data-action]'))x.disabled=true;const body={action:b.dataset.action};if(b.dataset.source)body.source=b.dataset.source;if(body.action==='recover'){body.runtime_id=current.runtime_id;body.candidate_digest=current.candidate_digest;}
  try{const response=await fetch('/api/admin/current',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok){$('feedback').textContent=data.reason||'Control failed. Inspect current status.';}else{$('feedback').textContent=body.action==='recover'?'Fresh runtime recorded. Previous reviews expired.':body.action==='stop'?'Dispatch revoked. Inspect cleanup status.':'Affected source paused. Independent paths continue.';render(data);}}
  catch{$('feedback').textContent='Control outcome unknown. Inspect status before trying again.';}finally{busy=false;if(current)render(current);await refresh();}
});
refresh();setInterval(refresh,5000);
