import {el,venues,periods,markets,american,age,metricText,metricExact,StableOrder,renderDetails,coverageDescription,grossMetric,readableState,reasonText} from './comparison-board.js';
// EV/Arbs/Coverage are read-only projections of the same current state.
const $=id=>document.getElementById(id),view=document.body.dataset.view;
let data,busy=false,again=false,selected=null,ceiling='100',sortRequested=true;
const order=new StableOrder();
const announce=value=>{if($('announcement'))$('announcement').textContent=value;};
const filters=()=>Object.fromEntries(['league','market','venue','search','results','basis'].map(k=>[k,$(k)?.value||'']));
const metricKey=view==='arbs'?'buffered_minimum_return':'net_ev';
function review(row){return{event:{id:row.event_id,title:row.title},group:{id:row.group_id,period:row.period,market:row.market,period_boundary:row.period_boundary},outcome:{id:row.outcome_id,label:row.selection},quote:{...row.quote,calculations:{...row.quote.calculations,ev:grossMetric(row.quote,row.gross),net_ev:row.net_ev,conservative:row.conservative}},mode:data.mode};}
function modality(){const pane=$('details');if(!pane)return;pane.hidden=!selected;const narrow=selected&&matchMedia('(max-width:1050px)').matches;pane.toggleAttribute('aria-modal',Boolean(narrow));if(narrow)pane.setAttribute('role','dialog');else pane.removeAttribute('role');let n=pane;while(n.parentElement){for(const sibling of n.parentElement.children)if(sibling!==n)sibling.inert=Boolean(narrow);n=n.parentElement;}}
function close(){const origin=selected?.id;selected=null;modality();document.getElementById('inspect-'+origin)?.focus({preventScroll:true});}
async function changeSize(value){if(!/^\d+(\.\d{1,2})?$/.test(value)||Number(value)<=0){announce('Enter a positive dollar ceiling with up to two decimal places.');return;}ceiling=value;sortRequested=true;await pull();}
function limitingLabels(pair){const full=pair.details||{},labels=pair.state_labels||full.state_labels||{};return(pair.limiting_states||full.limiting_states||[]).map((id,index)=>readableState({[id]:pair.limiting_state_labels?.[index]||labels[id]},id));}
function pairDetails(pair){
  const pane=$('details'),active=document.activeElement?.id,scroll=pane.scrollTop;const prior=pane.querySelector('#comparison-ceiling')?.value;
  pane.replaceChildren();const back=el('button','Back','close');back.id='close-details';back.onclick=close;pane.append(back,el('h2',pair.title||'Selected arb scenario'));
  if(selected.expired)pane.append(el('p','No longer available. Last selected scenario retained for inspection.','notice'));
  const metric=pair.buffered_minimum_return||{},full=pair.details||metric.details||{},category=pair.category||metric.basis?.conditioning||'Conditional / inputs needed';
  pane.append(el('h3','Fully acquired portfolio estimate'),el('p',selected.expired?'Unavailable':metricText(metric)),el('p',category.replaceAll('_',' ')));
  const legs=el('section',undefined,'detail-section');legs.append(el('h3','Both selections and allocation'));for(const leg of pair.legs||[]){const q=leg.quote||{};legs.append(el('h4',(leg.selection||leg.label||'Selection')+' · '+(venues[leg.venue||q.venue]||leg.venue||q.venue)),el('p','Odds: '+(leg.odds||q.display?.american||'Unknown')),el('p','Quantity: '+(leg.quantity||'Unknown')+' · capital: $'+(leg.capital_usd||leg.deployed_capital_usd||full.one_leg_exposures?.[pair.legs.indexOf(leg)]?.deployed_capital_usd||'Unknown')),el('p','Native side: '+(leg.native_side||q.source?.native_side||'Unknown')),el('p','Leg revision: '+(leg.quote_revision||q.revision||leg.revision||'Unknown')));}pane.append(legs);
  const labels=pair.state_labels||full.state_labels||{},capital=pair.capital_denominator||metric.basis?.capital_denominator||full.denominator_usd,limiting=limitingLabels(pair).join(', ')||'Unknown state';
  pane.append(el('h3','Net calculation and worst state'),el('p','Deployed capital: $'+(capital||'Unknown')),el('p','Minimum net profit: $'+(full.minimum_return_usd||'Unknown')),el('p','Limiting state: '+limiting),el('p',(pair.truncated||full.search_truncated)?'Best evaluated allocation · partial search':full.search_label||'Evaluated within the declared search bounds'));
  const states=pair.states||full.state_profits_usd;if(states){const table=el('table',undefined,'scenario-table');const tr=el('tr');tr.append(el('th','State'),el('th','Net cashflow'));table.append(tr);for(const[state,cash]of Object.entries(states)){const line=el('tr');line.append(el('td',readableState(labels,state)),el('td',cash===null?'Unknown':typeof cash==='object'?JSON.stringify(cash):cash));table.append(line);}pane.append(table);}
  pane.append(el('h3','Fees, buffer, depth and size'),el('p','Both legs must be acquired at the modeled allocation. Partial fill is separate exposure.'),el('p','Depth: '+(full.depth?.depth_qualified?'Supplied original depth; no synchronized-fill promise':'Not qualified')),el('p','Native quantities: '+(full.native_quantities||[]).join(' + ')),el('p','Unknown states: '+((full.unknown_states||[]).map(id=>readableState(labels,id)).join(', ')||'None in the declared modeled partition')));
  for(const[index,cost]of(full.cost_summaries?.conservative||[]).entries()){const base=full.cost_summaries?.base?.[index]||{},summary=el('section',undefined,'detail-section');summary.append(el('h4','Leg '+(index+1)+' costs'),el('p','Acquisition: $'+(base.acquisition_usd??'Unknown')+' base → $'+(cost.acquisition_usd??'Unknown')+' buffered'),el('p','Entry fee: $'+(cost.entry_fee_usd??'Unknown')+' · rounding refund: $'+(cost.rounding_refund_usd??'Unknown')+' · net entry fee: $'+(cost.net_entry_fee_usd??'Unknown')));const fees=el('table',undefined,'scenario-table'),head=el('tr');head.append(el('th','State'),el('th','Payout'),el('th','Settlement fee'),el('th','Net profit'));fees.append(head);for(const[state,value]of Object.entries(cost.states||{})){const line=el('tr');for(const field of[readableState(labels,state),value.gross_return_usd,value.settlement_fee_usd,value.net_profit_usd])line.append(el('td',field===null||field===undefined?'Unknown':field));fees.append(line);}summary.append(fees);pane.append(summary);}
  if(full.buffers){const buffer=el('details');buffer.append(el('summary','Legal-price buffer movements'),el('pre',JSON.stringify(full.buffers,null,2)));pane.append(buffer);}
  const baseline=el('details');baseline.append(el('summary','Base and gross scenario comparison'));for(const[key,label]of[['base','Net before buffer'],['gross','Gross before fees']]){const result=full[key],scope=result?.conditional||result?.full;baseline.append(el('p',label+': minimum $'+(scope?.worst_case_return??'Unknown')+' · denominator $'+(scope?.return_denominator??'Unknown')));}pane.append(baseline);
  if(full.one_leg_exposures){const exposure=el('details');exposure.append(el('summary','One-leg / partial-fill exposure'));for(const[index,leg]of full.one_leg_exposures.entries()){exposure.append(el('h4','Leg '+(index+1)+' acquired alone'),el('p','Deployed capital: $'+(leg.deployed_capital_usd??'Unknown')));for(const[state,profit]of Object.entries(leg.state_profits_usd||{}))exposure.append(el('p',readableState(labels,state)+': '+(profit===null?'Unknown':'$'+profit)));}pane.append(exposure);}
  const form=el('form',undefined,'size-form'),label=el('label','Optional capital ceiling ($)'),input=el('input'),save=el('button','Apply size');input.id='comparison-ceiling';input.value=prior||ceiling;input.inputMode='decimal';label.append(input);save.type='submit';form.append(label,save);form.onsubmit=e=>{e.preventDefault();changeSize(input.value);};pane.append(form);
  const raw=el('details');raw.append(el('summary','Original scenarios and exact evidence'),el('pre',JSON.stringify(pair,null,2)));pane.append(raw);pane.scrollTop=scroll;if(active)document.getElementById(active)?.focus({preventScroll:true});
}
function select(row){selected={id:row.id,row,expired:false};if(view==='arbs')pairDetails(row);else renderDetails($('details'),review(row),close,null,{onSize:changeSize,ceiling});modality();$('close-details')?.focus();announce('Showing selected opportunity Details.');}
function held(){if(!selected)return;const row=(view==='arbs'?data.pairs:data.rows).find(x=>x.id===selected.id);if(row){selected.row=row;selected.expired=false;}else selected.expired=true;
  if(view==='arbs')pairDetails(selected.row);else renderDetails($('details'),{...review(selected.row),expired:selected.expired},close,null,{onSize:changeSize,ceiling});modality();}
function basisOptions(){if(!$('basis'))return;const prior=$('basis').value,groups=(data.groups||[]).filter(g=>g.basis_id!=='unavailable');const labels=groups.map(g=>{const b=g.rows[0]?.net_ev?.basis||{};const sources=[...new Set(g.rows.map(row=>venues[row.venue]||row.venue))].join(' / ');const conditioning=b.conditioning==='completed_decisive_results_only'?'Completed decisive only':(b.conditioning||'Conditional').replaceAll('_',' ');return[g.basis_id,sources+' · '+conditioning];});
  if(view==='arbs'){const categories=[...new Set((data.pairs||[]).map(p=>p.category||p.buffered_minimum_return?.basis?.conditioning||'unavailable'))];labels.splice(0,labels.length,...categories.map(c=>[c,c.replaceAll('_',' ')]));}
  const signature=JSON.stringify(labels);if($('basis').dataset.signature===signature)return;$('basis').dataset.signature=signature;$('basis').replaceChildren(...labels.map(([id,text])=>{const o=el('option',text);o.value=id;return o;}));if(!labels.length){const o=el('option','No qualified estimate basis');o.value='';$('basis').append(o);}
  $('basis').value=labels.some(x=>x[0]===prior)?prior:labels.find(x=>/conditional|completed|decisive/.test(x[1]))?.[0]||labels[0]?.[0]||'';
}
function rowsForView(){const f=filters();let rows=view==='arbs'?data.pairs||[]:data.rows||[];
  return rows.filter(r=>{if(f.league&&r.league!==f.league||f.market&&r.market!==f.market||f.venue&&view!=='arbs'&&r.venue!==f.venue)return false;
    if(f.venue&&view==='arbs'&&!(r.legs||[]).some(l=>(l.venue||l.quote?.venue)===f.venue))return false;
    if(f.search&&!((r.title||'')+' '+(r.selection||'')).toLowerCase().includes(f.search.toLowerCase()))return false;
    const m=r[metricKey],value=metricExact(m);if(f.results==='positive'&&(value===null||value[0]<=0n)||f.results==='unavailable'&&value!==null)return false;
    if(f.basis&&value!==null&&(view==='arbs'?(r.category||m.basis?.conditioning):r.basis_id)!==f.basis)return false;
    return true;});
}
function updateRow(node,row,index){node.dataset.id=row.id;let button=node.querySelector('button');if(!button){button=el('button');button.id='inspect-'+row.id;node.append(button);}button.onclick=()=>select(row);button.replaceChildren();
  const heading=el('div');heading.append(el('h3',(index+1)+'. '+(row.selection||row.title||'Selected pair')),el('p',row.title+(row.league?' · '+row.league:'')));
  if(view==='arbs'){node.classList.add('arb-card');const legs=el('div',undefined,'arb-legs');for(const leg of row.legs||[]){const q=leg.quote||{};legs.append(el('p',(leg.selection||leg.label||'Selection')+' · '+(venues[leg.venue||q.venue]||leg.venue||q.venue)+' '+(leg.odds||q.display?.american||'—')));}const result=el('div');result.append(el('strong',metricText(row.buffered_minimum_return),'ranking-result'),el('p',(row.category||row.buffered_minimum_return?.basis?.conditioning||'Conditional').replaceAll('_',' ')+' · limiting state '+(limitingLabels(row).join(', ')||'Unknown state')),el('p',(row.truncated||row.details?.search_truncated)?'Best evaluated allocation · partial search':'Best evaluated allocation · within declared bounds'));button.append(heading,legs,result);}
  else{heading.append(el('p',venues[row.venue]||row.venue),el('p','Source age at reading: '+age(row.quote)+(row.quote.stale?' · stale':row.quote.state==='stopped'?' · updates stopped':row.quote.state==='budget_delayed'?' · updates delayed':row.quote.state==='unavailable'?' · source unavailable':'')));const venue=el('div');venue.append(el('span','Venue odds','ranking-label'),el('strong',row.venue_odds||'—'));const reference=el('div');reference.append(el('span','Pinnacle','ranking-label'),el('strong',american(row.reference_odds)));const result=el('div');result.append(el('span','Est. net benchmark EV','ranking-label'),el('strong',metricText(row.net_ev),'ranking-result'),el('p',row.net_ev?.eligible?'Estimated · '+(row.net_ev.estimate_class||'standalone hypothetical').replaceAll('_',' '):reasonText(row.net_ev?.reason)));const modeled=row.quote.calculations?.direct_site_estimate;if(modeled?.eligible)result.append(el('small','Modeled conditional after-cost EV: '+modeled.display_value));const gross=grossMetric(row.quote,row.gross);if(gross?.eligible)result.append(el('br'),el('small','Gross decisive benchmark: '+metricText(gross)));button.append(heading,venue,reference,result);}
}
function drawRankings(){basisOptions();const note=$('basis-note');if(note){const basis=data.groups?.find(group=>group.basis_id===$('basis').value)?.rows[0]?.net_ev?.basis||{};note.textContent=(basis.probability_basis||'Probability basis unavailable').replaceAll('_',' ')+' · '+(basis.conditioning||'Conditioning unknown').replaceAll('_',' ')+' · $'+ceiling+' common ceiling · deployed capital · optional size in Details';}const root=$('rankings'),anchor=[...root.children].find(n=>n.getBoundingClientRect?.().bottom>0),anchorTop=anchor?.getBoundingClientRect?.().top;const rows=rowsForView(),ranked=order.apply(rows,{resort:sortRequested,key:metricKey});sortRequested=false;const active=document.activeElement?.id,old=new Map([...root.children].map(n=>[n.dataset.id,n]));const keep=new Set();for(const[rowIndex,row]of ranked.entries()){keep.add(row.id);let node=old.get(row.id);if(!node){node=el('article',undefined,'ranking-row');root.append(node);}updateRow(node,row,rowIndex);if(root.children[rowIndex]!==node)root.insertBefore(node,root.children[rowIndex]||null);}for(const node of [...root.children])if(!keep.has(node.dataset.id))node.remove();
  if(!rows.length){const f=filters(),empty=el('div',undefined,'empty');const title=f.results==='positive'?(view==='arbs'?'No positive buffered pairs in this scope':'No positive estimates in this scope'):f.results==='unavailable'?'No unavailable results in this scope':'No results match this scope';empty.append(el('h2',title));if(f.results==='positive'){empty.append(el('p','Zero, negative and unavailable results are hidden by the Positive filter.'));const all=el('button','Show all results');all.type='button';all.onclick=()=>{$('results').value='all';sortRequested=true;drawRankings();$('results').focus();};empty.append(all);}else empty.append(el('p','Try another sport, market, venue or game name.'));const link=el('a','Inspect source coverage');link.href='/current/coverage';const help=el('p');help.append(link);empty.append(help);root.append(empty);} 
  if(anchor?.parentElement===root&&Number.isFinite(anchorTop))window.scrollBy?.(0,anchor.getBoundingClientRect().top-anchorTop);if(active)document.getElementById(active)?.focus({preventScroll:true});$('flow').textContent=rows.length+' '+(view==='arbs'?'evaluated pairs':'selection / venue opportunities')+' · $'+ceiling+' ceiling';if($('resort')){$('resort').textContent=order.pending?'Re-sort · '+order.pending+' updates':'Re-sort';$('resort').disabled=!order.pending;$('resort').hidden=!order.pending;}
  if($('limits'))$('limits').textContent='Search scope: up to '+(data.limits?.candidate_pairs??'unknown')+' pairs, '+(data.limits?.allocation_evaluations??'unknown')+' allocation evaluations and '+(data.limits?.returned_results??'unknown')+' returned results. A truncated search reports the best evaluated allocation.';$('test-notice').hidden=data.mode!=='synthetic';held();
}
function drawCoverage(){if($('test-notice'))$('test-notice').hidden=data.mode!=='synthetic';const root=$('coverage');root.replaceChildren();const bySport=new Map();for(const cell of data.cells||[]){if(filters().league&&cell.sport!==filters().league||filters().venue&&cell.venue!==filters().venue)continue;if(cell.venue==='pinnacle')continue;bySport.set(cell.sport,[...(bySport.get(cell.sport)||[]),cell]);}
  for(const[sport,cells]of bySport){const card=el('section',undefined,'coverage-card');card.append(el('h2',sport));for(const cell of cells){const source=el('div',undefined,'coverage-source');source.append(el('strong',venues[cell.venue]||cell.venue),el('p',coverageDescription(cell)),el('p','Last check: '+(cell.latest?.checked_at||'Not checked')+' · quote freshness uses original price clocks'),el('p','Offered markets: '+(cell.latest?.offered?.markets??'Unknown')+' · admitted: '+cell.counts.admitted_quotes+' · displayed: '+cell.counts.displayed_quotes+' · filtered: '+cell.counts.filtered_quotes+' · rejected markets: '+cell.counts.rejected_markets+' · rejected quotes: '+(cell.counts.rejected_quotes??'Unknown')));const evidence=el('details');evidence.append(el('summary','Observation and mapping evidence'),el('pre',JSON.stringify(cell,null,2)));source.append(evidence);card.append(source);}root.append(card);}
  $('flow').textContent=data.totals.displayed_quotes+' displayed / '+data.totals.admitted_quotes+' admitted · '+data.totals.filtered_quotes+' filtered';
  if($('reference-coverage')){$('reference-coverage').replaceChildren();for(const cell of data.cells.filter(c=>c.venue==='pinnacle'&&(!filters().league||c.sport===filters().league)))$('reference-coverage').append(el('p',cell.sport+' · '+(cell.status||'not_checked').replaceAll('_',' ')+' · offered reference markets '+(cell.latest?.offered?.markets??'Unknown')+' · original source clocks '+(cell.latest?.source_clocks?.join(', ')||'Unknown')));}
}
async function pull(){if(busy){again=true;return;}busy=true;try{do{again=false;const f=filters(),params=new URLSearchParams();if(view==='coverage')for(const k of ['league','venue','market'])if(f[k])params.set(k,f[k]);if(view!=='coverage')params.set('ceiling',ceiling);const r=await fetch((view==='coverage'?'/api/coverage':'/api/comparison')+'?'+params);if(!r.ok)throw Error('Current comparison unavailable');const next=await r.json();if(view==='coverage'){if(next.schema!=='comparison-coverage-1')throw Error('Unsupported coverage contract');data=next;drawCoverage();}else{if(next.schema!=='comparison-metrics-1')throw Error('Unsupported metric contract');if(data&&next.runtime_id===data.runtime_id&&next.state_revision<data.state_revision)continue;if(data&&next.runtime_id!==data.runtime_id)sortRequested=true;data=next;drawRankings();}if($('action-feedback'))$('action-feedback').hidden=true;}while(again);}catch(error){$('flow').textContent=error.message;announce(error.message);const feedback=$('action-feedback');if(feedback){feedback.textContent='Comparison unavailable. Any displayed results are retained; check source status in Admin.';feedback.hidden=false;}}finally{busy=false;}}
$('filters')?.addEventListener('submit',e=>e.preventDefault());for(const key of ['league','market','venue','search','results','basis'])$(key)?.addEventListener(key==='search'?'input':'change',()=>{sortRequested=true;if(view==='coverage')pull();else if(data&&['search','results','basis'].includes(key))drawRankings();else pull();});$('resort')?.addEventListener('click',()=>{sortRequested=true;drawRankings();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected)close();if(e.key==='Tab'&&selected&&matchMedia('(max-width:1050px)').matches){const nodes=[...$('details').querySelectorAll('button,input,a,summary,select')].filter(n=>{if(n.disabled||n.closest('[hidden]'))return false;for(let p=n.parentElement;p&&p!==$('details');p=p.parentElement)if(p.tagName==='DETAILS'&&!p.open&&!(n.tagName==='SUMMARY'&&n.parentElement===p))return false;return n.getClientRects().length>0;});if(e.shiftKey&&document.activeElement===nodes[0]){nodes.at(-1)?.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){nodes[0]?.focus();e.preventDefault();}}});
const stream=new EventSource('/api/current/updates');stream.onmessage=pull;stream.onopen=pull;stream.onerror=()=>{$('flow').textContent='Reconnecting to current state';};window.addEventListener('pagehide',()=>stream.close());window.addEventListener('resize',modality);
$('stop-current')?.addEventListener('click',async()=>{const b=$('stop-current');b.disabled=true;try{const r=await fetch('/api/admin/current',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'stop'})});if(!r.ok)throw Error('Stop unavailable');announce('Updates stopped. Accounting preserved.');b.textContent='Updates stopped';await pull();}catch(e){announce(e.message);const feedback=$('action-feedback');if(feedback){feedback.textContent=e.message+' · Check source status in Admin before retrying.';feedback.hidden=false;}b.disabled=false;}});modality();pull();
