// Compact comparison consumer. All inputs are shared current state; no acquisition.
export const venues={kalshi:'Kalshi',polymarket_us:'Polymarket US',novig:'Novig',prophetx:'ProphetX'};
export const periods={full_game:'Full game',first_half:'First half',second_half:'Second half',first_quarter:'First quarter'};
export const markets={winner:'Winner',spread:'Spread',total:'Total'};
export const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(className)n.className=className;return n;};
const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])])):value;
const stable=value=>JSON.stringify(canonical(value));
export function rational(value){
  if(typeof value!=='string'||value.length>256)throw Error('Exact string required');
  if(/^-?\d+\/\d+$/.test(value)){const [n,d]=value.split('/').map(BigInt);if(d<=0n)throw Error('Positive denominator required');return[n,d];}
  if(!/^-?\d+(\.\d+)?$/.test(value))throw Error('Exact decimal required');
  const negative=value.startsWith('-'),parts=(negative?value.slice(1):value).split('.');
  return[(negative?-1n:1n)*BigInt(parts.join('')),10n**BigInt(parts[1]?.length||0)];
}
export function metricExact(metric){if(metric?.eligible!==true)return null;const x=metric.exact;if(!x||typeof x.numerator!=='string'||typeof x.denominator!=='string')throw Error('Eligible result needs exact value');return rational(x.numerator+'/'+x.denominator);}
export function compareMetrics(a,b){const x=metricExact(a),y=metricExact(b);if(x===null)return y===null?0:1;if(y===null)return-1;const d=x[0]*y[1]-y[0]*x[1];return d>0n?-1:d<0n?1:0;}
export function sortRows(rows,key='net_ev'){return[...rows].sort((a,b)=>compareMetrics(a[key],b[key])||a.id.localeCompare(b.id));}
export class StableOrder{
  constructor(){this.ids=[];this.pending=0;}
  apply(rows,{resort=false,key='net_ev'}={}){const exact=sortRows(rows,key),known=new Map(rows.map(r=>[r.id,r]));
    if(resort||!this.ids.length)this.ids=exact.map(r=>r.id);
    else this.ids=[...this.ids.filter(id=>known.has(id)),...exact.filter(r=>!this.ids.includes(r.id)).map(r=>r.id)];
    this.pending=exact.reduce((n,row,i)=>n+(row.id!==this.ids[i]?1:0),0);
    return this.ids.map(id=>known.get(id));
  }
}
export function comparableBasis(metric){if(metric?.eligible!==true)return null;const b=metric.basis||{};const keys=['conditioning','probability_basis','size_basis','fee_basis'];if(keys.some(k=>b[k]===undefined||b[k]===null))return null;return stable(Object.fromEntries(keys.map(k=>[k,b[k]])));}
export function bestMetric(quotes,venue=''){
  const candidates=Object.values(quotes).flat().filter(q=>!venue||q.venue===venue);
  const list=candidates.filter(q=>metricExact(q.calculations?.net_ev)!==null);
  const bases=new Set(list.map(q=>comparableBasis(q.calculations.net_ev)));
  if(!list.length){const reasons=[...new Set(candidates.map(q=>q.calculations?.net_ev?.reason||'Net inputs needed'))];return{eligible:false,reason:reasons.join('; '),selected_quote_id:null,selected_venue:null};}
  if(bases.size!==1||bases.has(null))return{eligible:false,reason:'Separate estimate bases',selected_quote_id:null,selected_venue:null};
  list.sort((a,b)=>compareMetrics(a.calculations.net_ev,b.calculations.net_ev)||a.id.localeCompare(b.id));
  return{...list[0].calculations.net_ev,selected_quote_id:list[0].id,selected_venue:list[0].venue};
}
export function american(decimal){if(decimal===null||decimal===undefined)return'—';try{const[n,d]=rational(decimal),a=n-d;if(a<=0n)return'—';const positive=n>=2n*d,num=positive?a*100n:d*100n,den=positive?d:a;const rounded=(num*2n+den)/(den*2n);return(positive?'+':'−')+rounded;}catch{return'—';}}
export function quoteText(q){return q?.display?.supported===false?'Conversion unavailable':q?.display?.american||'—';}
export function referenceOf(q){return[q?.sharp_reference,q?.calculations?.net_ev?.details?.reference,q?.calculations?.net_ev?.details?.natural?.details?.reference].find(ref=>ref&&(ref.selected_odds||ref.odds?.[ref.selected]))||{};}
export function grossMetric(q,fallback){return[q?.calculations?.ev,q?.calculations?.net_ev?.details?.gross_decisive_benchmark,fallback].find(metric=>metric?.eligible===true)||q?.calculations?.ev||fallback;}
export function readableState(labels,id){const label=labels?.[id];return typeof label==='string'&&label.trim()&&label!==id?label:'Unknown state';}
export function age(q){if(!q?.times?.source_at||q.age_seconds===null||q.age_seconds===undefined)return'Age unknown';const s=Math.max(0,Math.floor(q.age_seconds));return s<60?s+'s':s<3600?Math.floor(s/60)+'m':Math.floor(s/3600)+'h';}
export function sideMeaning(q){const side=q?.source?.native_side?.toUpperCase();return['YES','NO','LONG','SHORT'].includes(side)?side:'';}
const shortReason=reason=>{const r=String(reason||'Inputs needed').toLowerCase();if(/capacity/.test(r))return'Binding capacity';if(/fee|cost|mandatory|charge/.test(r))return'Fee needed';if(/reference|pinnacle/.test(r))return'Reference needed';if(/age|old|expired|clock/.test(r))return'Too old / age unknown';if(/probability|partition|tie|push/.test(r))return'Probability needed';if(/depth/.test(r))return'Depth needed';if(/mapping|identity|link/.test(r))return'Mapping needed';if(/payout|settlement/.test(r))return'Payout needed';if(/grid|increment|quantity/.test(r))return'Legal size needed';if(/separate estimate/.test(r))return'Separate bases';return'Inputs needed';};
export function metricText(m){return m?.eligible?(m.display_value||m.value+'%'):'— '+shortReason(m?.reason);}
export function reasonText(reason){
  const r=String(reason||'Comparison inputs are not bound for this quote');
  if(r.includes(';'))return [...new Set(r.split(';').map(value=>reasonText(value.trim())))].join('; ');
  const labels={selection_binding_unverified:'Event and selection binding is unverified',comparison_inputs_unbound:'Comparison inputs are not bound for this quote',target_size_depth_insufficient:'Available depth is below the comparison size',depth_inputs_unavailable:'Original depth inputs are unavailable',quote_not_available:'This quote is unavailable',comparison_capital_ceiling_exceeded:'This allocation exceeds the capital ceiling',native_minimum_exceeds_depth:'Available depth is below the venue minimum'};
  Object.assign(labels,{
    selected_US_refdata_scale_minimum_tick_absent:'Selected instrument priceScale, fractionalQtyScale, minimumTradeQty and tickSize are missing',
    selected_Kalshi_price_ranges_quantity_precision_unqualified:'Selected Kalshi price ranges, quantity grid and account precision need qualification',
    selected_participant_channel_mandatory_cost_scope_unqualified:'Standard direct-site retail: published mandatory transaction charges need qualification',
    execution_channel_and_mandatory_charges_unqualified:'Standard direct-site retail: published mandatory transaction charges need qualification',
    execution_channel_and_mandatory_fee_terms_unqualified:'Standard direct-site retail: published fee terms need qualification',
    direct_site_cost_case_modeled_total_charges_unverified:'Standard direct-site costs are modeled; published retail-wide settlement exemption or additional charges remain unestablished',
    selected_standard_direct_site_published_fee_terms_unqualified:'Standard direct-site retail fee schedule and mandatory transaction charges need qualification',
    selected_standard_direct_site_published_rate_rounding_and_charges_unqualified:'Standard direct-site retail rate, rounding and mandatory transaction charges need qualification',
    selected_period_overtime_completion_terms_unqualified:'Selected period, overtime and completion terms need qualification',
    source_selected_US_reference_scales_required:'Selected US price and quantity scales are required',
    source_selected_US_refdata_attachment_unqualified:'US reference data does not qualify the exact selected instrument',
    source_selected_US_refdata_grid_conflict:'Selected US reference data conflicts with the calculation grid',
    source_selected_US_wire_quantity_increment_unqualified:'Selected US wire quantity increment needs qualification',
    retained_pinnacle_candidate_occurrence_edge_unqualified:'Retained NFL Pinnacle prices exist, but the exact provider-to-game link and quote applicability are unqualified'
  });
  for(const[code,label]of Object.entries(labels))if(r===code||r.endsWith(':'+code))return label;
  if(/^[a-z][a-z0-9_]{1,159}$/.test(r)){const words=r.replaceAll('_',' ');return words[0].toUpperCase()+words.slice(1);}
  return /[_:]|quote:/.test(r)?'Comparison input needs qualification; inspect original evidence':r;
}
export function fillPrice(button,q){button.replaceChildren(el('strong',quoteText(q),'american'));const side=sideMeaning(q);if(side)button.append(el('span',side,'native-side'));button.append(el('small',age(q)+(q.stale?' · stale':q.state==='stopped'?' · stopped':q.state==='budget_delayed'?' · delayed':''),'age'));button.setAttribute('aria-label',(venues[q.venue]||q.venue)+', '+quoteText(q)+(side?', '+side:'')+', original source age '+age(q)+', inspect Details');}
export function canonicalGroups(event){
  const buckets=new Map();for(const group of event.groups){const key=stable([group.market,group.period,group.period_boundary,group.line,group.anchor_participant]);let b=buckets.get(key);if(!b){b={id:key,group,rows:new Map()};buckets.set(key,b);}
    for(const outcome of group.outcomes){const id=stable([outcome.participant,outcome.predicate,outcome.signed_line]);let row=b.rows.get(id);if(!row){row={id,outcome,group,quotes:{}};b.rows.set(id,row);}
      for(const q of [...Object.values(outcome.quotes),...Object.values(outcome.alternatives||{}).flat()]){row.quotes[q.venue]||=[];if(!row.quotes[q.venue].some(x=>x.id===q.id))row.quotes[q.venue].push(q);}
    }
  }return[...buckets.values()].map(b=>({...b,rows:[...b.rows.values()]}));
}
export function reconcileBoard(root,payload,filters,onSelect,selectedId){
  const focusedId=document.activeElement?.id,focusedQuote=document.activeElement?.dataset?.quoteId;
  const events=payload.events.filter(e=>(!filters.league||e.league===filters.league)&&e.title.toLowerCase().includes((filters.search||'').toLowerCase()));
  const buttons=new Map(),liveCards=new Set();let rows=0;
  for(const event of events){const groups=canonicalGroups(event).filter(x=>(!filters.market||x.group.market===filters.market)&&(!filters.period||x.group.period===filters.period));if(!groups.length)continue;
    liveCards.add(event.id);let card=[...root.children].find(n=>n.dataset.id===event.id);if(!card){card=el('section',undefined,'game-card');card.dataset.id=event.id;root.append(card);}
    const priorButtons=new Map([...card.querySelectorAll('[data-quote-id]')].map(n=>[n.dataset.quoteId,n]));const disclosures=new Set([...card.querySelectorAll('details[open]')].map(n=>n.dataset.scope));
    const children=[el('h2',event.title),el('p',event.league+' · '+new Date(event.start_at).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET','game-meta')];
    for(const block of groups){children.push(el('h3',(periods[block.group.period]||block.group.period)+' · '+(markets[block.group.market]||block.group.market)+(block.group.line?' '+block.group.line:''),'market-heading'));
      const regular=block.rows.filter(r=>r.outcome.predicate!=='not_win'),other=block.rows.filter(r=>r.outcome.predicate==='not_win');
      const tableFor=list=>{const table=el('table',undefined,'comparison-table');const head=el('thead'),tr=el('tr');for(const label of ['Selection',...Object.values(venues),'Pinnacle','Est. net EV'])tr.append(el('th',label));head.append(tr);table.append(head);const body=el('tbody');table.append(body);
        for(const row of list){rows++;const line=el('tr');line.append(el('th',row.outcome.label,'selection-name'));const all=row.quotes;
          for(const[v,label]of Object.entries(venues)){const cell=el('td');cell.dataset.label=label;const qs=(!filters.venue||filters.venue===v)?all[v]||[]:[];
            if(!qs.length){const state=payload.source_status?.[v];cell.append(el('span',filters.venue&&filters.venue!==v?'— Filtered':state?.state==='error'?'— Source failed':'— No quote','missing-price'));}
            for(const q of qs){const button=priorButtons.get(q.id)||el('button',undefined,'price-button');button.type='button';button.dataset.quoteId=q.id;button.review={event,group:row.group,outcome:row.outcome,quote:q,mode:payload.mode};button.onclick=()=>onSelect(button.review);fillPrice(button,q);button.classList.toggle('selected',q.id===selectedId);cell.append(button);buttons.set(q.id,{button,q,quotes:all});}
            line.append(cell);
          }
          const net=bestMetric(all,filters.venue),chosen=Object.values(all).flat().find(q=>q.id===net.selected_quote_id)||Object.values(all).flat()[0],ref=referenceOf(chosen);const reference=el('td');reference.dataset.label='Pinnacle';reference.append(el('strong',american(ref.selected_odds||ref.odds?.[ref.selected])));line.append(reference);
          const metric=el('td');metric.dataset.label='Est. net EV';const inspect=el('button',metricText(net),'net-cell');inspect.id='net-'+row.outcome.id;inspect.type='button';inspect.dataset.selectedVenue=net.selected_venue||'';if(chosen)inspect.onclick=()=>onSelect({event,group:row.group,outcome:row.outcome,quote:chosen,mode:payload.mode});else inspect.disabled=true;inspect.append(el('small',net.eligible?(venues[net.selected_venue]+' · Estimated'):'Inspect Details'));metric.append(inspect);line.append(metric);body.append(line);
        }return table;};
      if(regular.length)children.push(tableFor(regular));if(other.length){const fold=el('details',undefined,'other-native');fold.dataset.scope=block.id;fold.open=disclosures.has(block.id);fold.append(el('summary','Other native contracts · NO / not-win meaning'),el('p','These selections preserve their own predicate and tie / refund payouts.'),tableFor(other));children.push(fold);}
    }
    const focus=document.activeElement?.dataset?.quoteId;card.replaceChildren(...children);if(focus&&buttons.has(focus))buttons.get(focus).button.focus({preventScroll:true});
  }
  for(const card of [...root.children])if(!liveCards.has(card.dataset.id))card.remove();
  if(focusedQuote&&buttons.has(focusedQuote))buttons.get(focusedQuote).button.focus({preventScroll:true});else if(focusedId)document.getElementById(focusedId)?.focus({preventScroll:true});
  return{events:events.filter(e=>liveCards.has(e.id)),rows,buttons};
}
export const reconcileChangedBoard=(root,payload,filters,onSelect,selectedId)=>reconcileBoard(root,payload,filters,onSelect,selectedId);
const section=(root,title)=>{const n=el('section',undefined,'detail-section');n.append(el('h3',title));root.append(n);return n;};
const fact=(root,label,value)=>{const line=el('p');line.append(el('strong',label+': '),el('span',value===null||value===undefined?'Unknown':typeof value==='string'?value:JSON.stringify(value)));root.append(line);};
const money=value=>{if(value===null||value===undefined)return'Unknown';try{const[n,d]=rational(String(value));return'$'+(Number(n)/Number(d)).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:6});}catch{return'$'+value;}};
const formValues=new Map();
export function renderDetails(root,review,onClose,onLatest,options={}){
  const q=review.quote,originalMetric=q.calculations?.net_ev||{},metric=review.expired?{...originalMetric,eligible:false,reason:'No longer available'}:originalMetric,meta=metric.details||{},detail={...meta.natural?.details,...meta},basis=metric.basis||{},scenario=detail.scenario,costInput=detail.costs||{},costs=detail.state_costs||costInput.states,buffer=detail.buffer||{};
  const active=root.contains(document.activeElement)?document.activeElement?.id:null,scroll=root.scrollTop,opened=new Set([...root.querySelectorAll('details[open]')].map(n=>n.dataset.disclosure));
  const oldInput=root.querySelector('#comparison-ceiling');if(oldInput)formValues.set(q.id,oldInput.value);
  root.replaceChildren();root.classList.toggle('expired',Boolean(review.expired));const top=el('div',undefined,'detail-top');const close=el('button','Back','close');close.id='close-details';close.type='button';close.onclick=onClose;top.append(close,el('h2',review.outcome?.label||review.selection||'Selected bet'),el('p',review.event?.title||review.title||''));top.append(el('p',(review.mode==='synthetic'?'Synthetic example · ':'')+(venues[q.venue]||q.venue)+' · '+quoteText(q)+(sideMeaning(q)?' · '+sideMeaning(q):'')));root.append(top);
  const notice=el('p',review.expired?'No longer available. These are the last selected inputs.':'','notice');notice.id='selection-notice';notice.hidden=!review.expired;root.append(notice);
  const nativeWording=scenario?.legs?.[0]?.selection?.native?.original_wording;

  const calculation=section(root,'Net calculation');fact(calculation,'Estimated net benchmark EV',metricText(metric));if(!metric.eligible)fact(calculation,'Needed input',reasonText(metric.reason));fact(calculation,'Expected profit',money(detail.expected_profit_usd||meta.natural?.expected_profit_usd||metric.expected_profit_usd));fact(calculation,'Deployed denominator',money(basis.capital_denominator||metric.capital_denominator||detail.capital?.deployed_capital_usd));fact(calculation,'Estimate',(metric.estimate_class||'Unavailable').replaceAll('_',' '));fact(calculation,'Gross decisive benchmark',metricText(grossMetric(q)));fact(calculation,'Conservative result',metricText(q.calculations?.conservative));
  if(options.onSize){const form=el('form',undefined,'size-form');const label=el('label','Optional capital ceiling ($)');const input=el('input');input.id='comparison-ceiling';input.type='text';input.inputMode='decimal';input.value=formValues.get(q.id)||options.ceiling||'100';input.autocomplete='off';label.append(input);const save=el('button','Apply size');save.type='submit';const feedback=el('p','','size-feedback');feedback.id='size-feedback';feedback.setAttribute('role','status');input.setAttribute('aria-describedby','size-feedback');form.append(label,save,feedback);form.onsubmit=e=>{e.preventDefault();formValues.set(q.id,input.value);if(!/^\d+(\.\d{1,2})?$/.test(input.value)||Number(input.value)<=0){feedback.textContent='Enter a positive dollar ceiling with up to two decimal places.';feedback.classList.add('error');input.setAttribute('aria-invalid','true');input.focus();return;}input.removeAttribute('aria-invalid');feedback.classList.remove('error');feedback.textContent='Updating estimate…';Promise.resolve(options.onSize(input.value)).then(()=>{const latest=root.querySelector('#size-feedback');if(latest&&!latest.classList.contains('error'))latest.textContent='';},()=>{feedback.textContent='Size estimate unavailable. Check the current calculation and retry.';feedback.classList.add('error');});};calculation.append(form);}
  const selected=section(root,'Selected bet and native meaning');fact(selected,'Venue',venues[q.venue]||q.venue);if(q.provenance?.mode!=='synthetic'&&q.venue!=='pinnacle')fact(selected,'Trading scope','Standard direct-site retail');fact(selected,'Odds',quoteText(q));fact(selected,'Native side',sideMeaning(q)||q.source?.native_side);fact(selected,'Meaning',review.outcome?.label||review.selection);if(nativeWording&&nativeWording.length<=160)fact(selected,'Original selection',nativeWording);fact(selected,'Scope',(review.group?.period_boundary||review.period||'Unknown').replaceAll('_',' '));
  const reference=section(root,'Pinnacle reference');const ref=referenceOf(q),selectedOdds=ref.selected_odds||ref.odds?.[ref.selected],opposingOdds=ref.opposing_odds||ref.odds?.[ref.selected===0?1:0];fact(reference,'Selected odds',american(selectedOdds)+' · original '+(selectedOdds||'Unknown'));fact(reference,'Opposing odds',opposingOdds?american(opposingOdds)+' · original '+opposingOdds:'Unknown');fact(reference,'Method','Proportional no-vig market benchmark');fact(reference,'Conditioning',basis.conditioning||metric.conditioning||'Unknown decisive / tie mass');fact(reference,'Source clock',ref.source_at||ref.selected_source_at||ref.original_clocks||'Unknown');
  const statuses=q.comparison_input_status||detail.input_status||{};if(Object.keys(statuses).length){const inputs=section(root,'Input availability');for(const[kind,item]of Object.entries(statuses))fact(inputs,kind[0].toUpperCase()+kind.slice(1),item.status.replaceAll('_',' ')+' · '+reasonText(item.reason));}
  const retail=statuses.quantity?.public_retail;if(retail){const data=retail.metadata||{},publicFacts=section(root,'Public retail metadata observation');fact(publicFacts,'Observed',retail.observed_at);if(retail.retained_observation_bound){fact(publicFacts,'Metadata source',retail.metadata_receipt?.url);fact(publicFacts,'Metadata interval',retail.effective_from+' to '+retail.effective_until);fact(publicFacts,'Response SHA-256',data.response_sha256);}fact(publicFacts,'Minimum / increment',data.minimumTradeQty+' / '+data.minimumTradeQty+' contracts');fact(publicFacts,'Price tick','$'+data.orderPriceMinTickSize+' per contract');fact(publicFacts,'Single taker coefficient',data.feeCoefficient+' · decimal contracts and dollar prices');fact(publicFacts,'Settlement terms',data.description);fact(publicFacts,'Remaining costs',statuses.fee?.direct_site_case?'Retail-wide settlement exemption or additional transaction charge schedule remains unestablished; standard case is modeled':'Mandatory settlement and other charges need qualification');fact(publicFacts,'Applicability',retail.retained_observation_bound?(statuses.quantity.status==='available_and_bound'?'Bound to exact retained Long revision '+retail.quote_revision+' at this saved evaluation; no live freshness claim':'Exact retained observation; metadata is outside its interval or the binding is unresolved'):retail.historical_applicability?'Historical applicability evidenced':'Separate metadata observation; original price clock is unchanged; historical applicability is unqualified');fact(publicFacts,'Event linkage',statuses.identity?.public_event?'Complete exact event membership retained; see event observation':'Complete exact event membership evidence unavailable');}
  const chargeAudit=statuses.fee?.charge_completeness;if(chargeAudit&&!statuses.fee?.direct_site_case){const charges=section(root,'Mandatory charge completeness');fact(charges,'Published clearing fees',chargeAudit.published_clearing.description);fact(charges,'Notice receipt',chargeAudit.published_clearing.original_receipt_at);fact(charges,'Selected settlement charges','Unknown; published clearing exemption does not establish every settlement charge');fact(charges,'Trading scope','Standard direct-site retail selected; total published transaction costs remain unqualified');for(const[label,value]of Object.entries(chargeAudit.missing_facts||{}))fact(charges,label.replaceAll('_',' '),value);fact(charges,'Transaction scope',chargeAudit.transaction_scope.conditional_or_optional);fact(charges,'Remaining published fact','Retail-wide settlement exemption or additional mandatory transaction charge schedule');fact(charges,'Authority','Diagnostic evidence only; no cost profile, net EV or renewed review interval');}
  const eventFacts=statuses.identity?.public_event;if(eventFacts){const eventSection=section(root,'Public event membership observation'),occurrence=eventFacts.occurrence||{},scope=eventFacts.scope||{},member=eventFacts.selected||{};fact(eventSection,'Membership','Event '+eventFacts.event_id+' contains market '+eventFacts.market_id);fact(eventSection,'Selected side',member.native_key?.[3]+' / '+member.native_key?.[4]+' · '+member.name+' · '+(member.role||'Role unknown'));fact(eventSection,'Occurrence','Game '+(occurrence.game_id||'Unknown')+' · '+(occurrence.provider_game_id||'Provider occurrence unknown'));fact(eventSection,'Scheduled',occurrence.scheduled_start);fact(eventSection,'Meaning',(scope.period||'Period unknown')+' · '+(scope.selection_meaning||'Selection unknown')+' · overtime '+scope.overtime);fact(eventSection,'Observed',eventFacts.provenance?.response_finished_at);fact(eventSection,'Metadata interval',eventFacts.status==='available_and_bound'?'Available at this evaluation boundary until '+eventFacts.effective_until:'Outside the metadata interval or attachment unresolved');fact(eventSection,'Historical quote','Historical applicability unqualified; original price and source clock retained');fact(eventSection,q.sharp_reference?'Reference applicability':'Reference gap',q.sharp_reference?'Exact Pinnacle opposition is attached to this observation; eligibility uses its original source and receipt clocks.':statuses.reference?.retained_candidate?'Retained NFL Pinnacle opposition exists. Occurrence, grading and reference age remain unqualified at this original quote boundary.':'Exact cross-source occurrence and Pinnacle opposition remain unqualified');}
  const prospective=statuses.reference?.prospective_review||statuses.reference?.retained_candidate?.prospective_review;if(prospective){const currentReview=section(root,'Separate prospective occurrence review');fact(currentReview,'Review','Recorded manual review of official schedule, game page and exact source identities');fact(currentReview,'Game context',prospective.venue);fact(currentReview,'Reuse interval',prospective.effective_from+' to '+prospective.effective_until+'; re-review after expiry');fact(currentReview,'Pinnacle rules',prospective.rules);fact(currentReview,'Rule date',prospective.rule_version);fact(currentReview,'Comparison',q.sharp_reference?'This observation has an exact Pinnacle reference for conditional decisive win/loss gross EV. Tie and exceptional mass, costs and execution depth remain separate.':'Needs a newly observed native quote and contemporaneous Pinnacle opposition. Paid acquisition remains disabled.');fact(currentReview,'Original quote','This review supplies no historical authority or reference price. Original Long and Short remain separate.');}
  const direct=statuses.fee?.direct_site_case;if(direct){const costs=section(root,'Standard direct-site retail costs');fact(costs,'Trading scope','Direct trading on the venue site · standard published retail fees · one modeled taker order/fill');fact(costs,'Published entry fee','0.0695 × contracts × price × (1 − price); half-even cents, cumulative order cap; charged at execution once');fact(costs,'Effective entry schedule',direct.entry_schedule_from);fact(costs,'Published clearing fees',direct.published_clearing.description+' · clearing-member scope');fact(costs,'Cost case',direct.assumption);fact(costs,'Remaining published fact',direct.remaining_published_fact);fact(costs,'Excluded activity',direct.conditional_or_optional);const estimate=q.calculations?.direct_site_estimate;fact(costs,'Modeled conditional after-cost EV',estimate?.eligible?estimate.display_value:reasonText(estimate?.reason));if(estimate?.eligible){fact(costs,'Conditional basis','Completed decisive win/loss only; actual tie/exceptional mass and full payout equivalence remain unknown');fact(costs,'Size',estimate.quantity+' contracts at $'+estimate.price+' · $'+estimate.ceiling_usd+' optional ceiling');fact(costs,'Acquisition / entry / deployed',money(estimate.acquisition_usd)+' / '+money(estimate.entry_fee_usd)+' / '+money(estimate.deployed_usd));fact(costs,'Assumed additional transaction charges','$0 settlement; $0 other mandatory charges · modeled, not verified');fact(costs,'Independent gates',estimate.independent_gates.join('; '));fact(costs,'Evaluation',estimate.evaluation_at+' · saved evaluation; no current freshness claim');}}
  const entry=statuses.fee?.public_entry_example;if(entry){const example=section(root,'Public entry fee example');fact(example,'Hypothetical single fill',entry.quantity+' contracts at $'+entry.price);fact(example,'Entry fee only',money(entry.entry_fee_usd));fact(example,'Other charges','Settlement and other mandatory charges unknown; this example does not qualify net EV');}
  const funding=section(root,'Fees, buffer and size');fact(funding,'Portfolio',costInput.assumption||'Standalone hypothetical portfolio unless complete scoped positions are bound');if(detail.fee_qualification)fact(funding,'Fee qualification',detail.fee_qualification);if(detail.quantity_grid_qualification)fact(funding,'Size qualification',detail.quantity_grid_qualification);if(detail.quantity_grid)fact(funding,'Quantity grid',detail.quantity_grid.minimum_native+' minimum / '+detail.quantity_grid.increment_native+' increment');fact(funding,'Comparison ceiling',money(basis.size_basis?.ceiling_usd||basis.size_basis?.common_capital_ceiling_usd||options.ceiling||'100'));fact(funding,'Quantity',costInput.size_basis?.native_quantity||detail.native_quantity||basis.size_basis?.native_quantity||'Not calculated while required inputs are unavailable');if(detail.fill_basis)fact(funding,'Fill basis',detail.fill_basis==='hypothetical_one_order'?'Modeled one-order standalone estimate · no observed fills':detail.fill_basis);fact(funding,'Acquisition',money(costInput.acquisition_usd));fact(funding,'Entry fee',money(costInput.entry_fee_usd));fact(funding,'Deterministic rounding refund',money(costInput.rounding_refund_usd));fact(funding,'Net entry fee',money(costInput.net_entry_fee_usd));fact(funding,'Idle ceiling residual',money(detail.unused_ceiling_usd||costInput.capital?.residual_ceiling_usd||detail.capital?.residual_ceiling_usd));fact(funding,'Movement',buffer.movement?.available?money(buffer.movement.movement_per_dollar_face)+' per $1 face · adverse price '+buffer.movement.adverse_normalized_price:'$0.01 per $1 face or the larger evidenced legal tick; repriced on the legal grid');fact(funding,'Paired sensitivity denominator',money(buffer.sensitivity?.denominator_usd));fact(funding,'Returned base allowance',money(buffer.sensitivity?.base_refundable_sensitivity_allowance_usd));fact(funding,'Depth',buffer.depth?.depth_qualified?'Supplied original depth qualified; no fill promise':'Depth not qualified');const limits=[...(detail.buffer_reasons||[]),...(buffer.reasons||[]),...(buffer.depth?.reasons||[])];if(limits.length)fact(funding,'Buffer / depth limits',[...new Set(limits.map(reasonText))].join('; '));

  if(buffer.supported_size_sensitivity?.native_quantity)fact(funding,'Separate depth-supported size',buffer.supported_size_sensitivity.native_quantity+' native units · Details sensitivity; funding and fees require separate qualification');
  const states=section(root,'Scenario cashflows'),labels=detail.state_labels||scenario?.state_labels||{};if(costs){const table=el('table',undefined,'scenario-table');const head=el('tr');for(const x of ['State','Payout','Fees','Net profit'])head.append(el('th',x));table.append(head);for(const[id,row]of Object.entries(costs)){const tr=el('tr');for(const x of [readableState(labels,id),row.gross_return_usd,row.settlement_fee_usd,row.net_profit_usd])tr.append(el('td',x===null||x===undefined?'Unknown':x));table.append(tr);}states.append(table);}else if(scenario){for(const state of scenario.state_ids||[])fact(states,readableState(labels,state),scenario.legs?.map(l=>l.receipts[state]??'Unknown').join(' + '));}else states.append(el('p',statuses.payout?.status==='available_and_bound'?'Completed-result payouts are qualified. Net cashflows await remaining inputs; exceptional cashflows remain unknown.':'Applicable state payouts are not bound. Unknown does not mean zero.'));
  const evidence=el('details',undefined,'original-evidence');evidence.dataset.disclosure='original';evidence.open=opened.has('original');evidence.append(el('summary','Original evidence and exact inputs'));const original=el('div');fact(original,'Native instrument / side',q.source?.native_outcome_id+' / '+q.source?.native_side);fact(original,'Original price',q.original?.value+' '+q.original?.units);fact(original,'Original payout',q.original?.payout+' '+q.original?.payout_units);fact(original,'Original price clock',q.times?.source_at);fact(original,'Receipt clock',q.times?.received_at);fact(original,'Quote revision',q.revision);fact(original,'Venue rules',q.rule_note);fact(original,'Fee basis',basis.fee_basis);fact(original,'Dependency revisions',basis.dependency_revisions);original.append(el('pre',JSON.stringify({source:q.source,reference:q.sharp_reference,metric,conservative:q.calculations?.conservative,provenance:q.provenance},null,2)));evidence.append(original);root.append(evidence);
  if(options.renderManual){const workspace=el('details');workspace.dataset.disclosure='manual';workspace.open=opened.has('manual');workspace.append(el('summary','Optional manual What-if'));const body=el('div');body.id='manual-workspace';options.renderManual(body);workspace.append(body);root.append(workspace);}
  root.scrollTop=scroll;if(active){const target=document.getElementById(active);if(target&&root.contains(target))target.focus({preventScroll:true});}
}
export function coverageDescription(cell){if(!cell.configured)return'Not configured for this sport';if(cell.display_reason==='filtered_out')return'Filtered · '+cell.counts.filtered_quotes+' admitted prices hidden';if(cell.status==='failed_source')return'Source failed · offerings unknown';if(cell.status==='rejected_payload')return'Source payload rejected';if(!cell.checked)return'Configured · not checked';if(cell.status==='no_offerings_returned')return'Checked empty · no offerings in this query';if(cell.counts.unresolved_mapping_quotes)return'Mapping needed · '+cell.counts.unresolved_mapping_quotes+' source-local prices';return'Checked · '+cell.counts.displayed_quotes+' displayed / '+cell.counts.admitted_quotes+' admitted';}
