import {NoticeGate} from './current-client.js';
import {el,venues,periods,reconcileBoard,renderDetails,fillPrice} from './board.js';
const $=id=>document.getElementById(id),schema='predict-current-1';
let payload,view,selection=null,snapshotBusy=false,snapshotAgain=false,connection='Connecting',payloadTick=performance.now();
const clientId=crypto.randomUUID(),notices=new NoticeGate(schema);
const filters=()=>Object.fromEntries(['league','market','period','venue','search'].map(k=>[k,$(k).value]));
const announce=text=>$('announcement').textContent=text;
async function request(url,body){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.reason||data.error||'Request unavailable'),{status:r.status,data});return data;}
function applicablePeriods(){const selected=$('period').value,available=new Set(['full_game']);for(const e of payload.events.filter(e=>!$('league').value||e.league===$('league').value))for(const g of e.groups)if(!$('market').value||g.market===$('market').value)available.add(g.period);$('period').replaceChildren(...[...available].map(k=>{const n=el('option',periods[k]||k.replaceAll('_',' '));n.value=k;return n;}));$('period').value=available.has(selected)?selected:'full_game';}
function empty(title,text){let n=$('board').querySelector('.empty');if(!n){n=el('div',undefined,'empty');$('board').append(n);}n.replaceChildren(el('h2',title),el('p',text));}
function draw(){if(!payload)return;const updates=$('source-updates');if(updates)updates.replaceChildren(...Object.entries(payload.source_status).map(([v,s])=>el('p',venues[v]+': '+(s.reason||s.state?.replaceAll('_',' ')||'Status unknown')+(s.next_due_at?' Next due '+new Date(s.next_due_at).toLocaleString('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit',month:'short',day:'numeric'})+' ET.':''))));view=reconcileBoard($('board'),payload,filters(),select,selection?.review.quote.id);$('count').textContent=view.events.length+' games · '+view.rows+' selections';$('test-notice').hidden=payload.mode!=='synthetic';
if(!payload.events.length){const state=payload.state;const reason=Object.values(payload.source_status).find(s=>s.reason)?.reason;empty(state==='connecting'?'Connecting to prices':state==='empty'?'No events available':'Current prices unavailable',Object.entries(payload.source_status).map(([venue,s])=>({kalshi:'Kalshi',polymarket_us:'Polymarket US',novig:'Novig',prophetx:'ProphetX'}[venue]||venue)+': '+s.state.replaceAll('_',' ')).join(' · ')||reason||'Available sources will appear here when the current provider is ready.');const help=el('p');const admin=el('a','Inspect sources and recovery in Admin');admin.href='/admin';admin.target='_blank';admin.rel='noopener';help.append(admin);$('board').querySelector('.empty').append(help);}
else if(!view.events.length)empty('No games match these filters','Try another league, period or team name. Clear filters to return to the board.');
const states=Object.values(payload.source_status).map(s=>s.state),allQuotes=payload.events.flatMap(e=>e.groups.flatMap(g=>g.outcomes.flatMap(o=>[...Object.values(o.quotes),...Object.values(o.alternatives||{}).flat()])));const summary=payload.state==='unavailable'?'Current provider unavailable':payload.state==='connecting'?'Connecting to prices':payload.state==='empty'?'No listed events':states.includes('budget_delayed')||allQuotes.some(q=>q.state==='budget_delayed')?'Some venue updates delayed':states.includes('error')?'Some sources unavailable':states.includes('stale')||allQuotes.some(q=>q.stale)?'Some quotes stale':allQuotes.some(q=>q.times.source_at===null)?'Some source ages unknown':payload.state==='degraded'||allQuotes.some(q=>q.state==='unavailable')?'Partial venue coverage':'Current price board';$('flow').textContent=summary+' · '+connection;checkSelection();}
function modal(){const narrow=selection&&matchMedia('(max-width:1050px)').matches;const d=$('details');d.hidden=!selection;if(narrow){d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');}else{d.removeAttribute('role');d.removeAttribute('aria-modal');}
// Inert each sibling on the path to body, preserving the Details subtree.
let current=d;while(current.parentElement){for(const sibling of current.parentElement.children)if(sibling!==current)sibling.inert=Boolean(narrow);current=current.parentElement;}
if(narrow&&!d.contains(document.activeElement))$('close-details')?.focus();}
async function release(id){if(!id)return;try{await request('/api/selections/'+id+'/release',{});}catch{/* Already expired/replaced is released. */}}
function currentReview(id){for(const event of payload.events)for(const group of event.groups)for(const outcome of group.outcomes)for(const quote of [...Object.values(outcome.quotes),...Object.values(outcome.alternatives||{}).flat()])if(quote.id===id)return {event,group,outcome,quote,mode:payload.mode};return null;}
function select(value){selection={review:currentReview(value.quote.id)};renderDetails($('details'),selection.review,closeDetails,null,{production:true,live:true,renderManual});draw();$('close-details').focus();modal();announce('Showing live price details for '+selection.review.outcome.label);}

function closeDetails(){const previous=selection,id=previous?.review.quote.id;selection=null;modal();$('details').classList.remove('expired');const p=el('div',undefined,'detail-placeholder');p.append(el('h2','A closer look'),el('p','Select any price to inspect its original quote, rules and supported calculations.'));$('details').replaceChildren(p);draw();(view?.buttons.get(id)?.button||$('search')).focus();}
function checkSelection(){if(!selection)return;const review=currentReview(selection.review.quote.id),n=$('selection-notice');if(!review){if(n){n.textContent='This price is currently unavailable.';n.hidden=false;}return;}
if(selection.lastLiveRevision===payload.state_revision)return;selection.lastLiveRevision=payload.state_revision;
const scroll=$('details').scrollTop,manual=$('manual-workspace'),focusId=document.activeElement?.id,focusSummary=document.activeElement?.tagName==='SUMMARY'?document.activeElement.textContent:null,opened=[...$('details').querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent),samePrice=selection.review.quote.revision===review.quote.revision;
selection.review=review;renderDetails($('details'),review,closeDetails,null,{production:true,live:true,renderManual});if(manual&&samePrice)$('manual-workspace')?.replaceWith(manual);for(const d of $('details').querySelectorAll('details'))if(opened.includes(d.querySelector('summary')?.textContent))d.open=true;$('details').scrollTop=scroll;if(focusId)$(focusId)?.focus({preventScroll:true});else if(focusSummary)[...$('details').querySelectorAll('summary')].find(n=>n.textContent===focusSummary)?.focus({preventScroll:true});
}
function renderManual(root){root.append(el('h3','Manual What-if'),el('p','Enter your own assumptions. This conditional normal win/loss scenario excludes pushes, refunds and exceptional settlement.'));
const form=el('form');for(const [key,label] of [['probability','Win probability (0–1)'],['entry_cost','Total entry costs ($)'],['win_cost','Total win settlement costs ($)'],['loss_cost','Total loss settlement costs ($)'],['quantity','Payout units']]){const field=el('label',label);const input=el('input');input.name=key;input.type='text';input.inputMode='decimal';input.required=true;input.autocomplete='off';field.append(input);form.append(field);}
const ack=el('label','I understand this assumes normal win/loss only');const check=el('input');check.type='checkbox';check.name='acknowledge_conditional';check.required=true;ack.append(check);form.append(ack);const submit=el('button','Calculate What-if','secondary');submit.type='submit';form.append(submit);const output=el('p','Assumptions needed');output.setAttribute('role','status');form.append(output);
form.addEventListener('submit',async e=>{e.preventDefault();const held=selection;if(!held||held.expired)return;const assumptions=Object.fromEntries(new FormData(form));assumptions.acknowledge_conditional=check.checked;submit.disabled=true;try{const q=held.review.quote;const lease=await request('/api/selections',{schema,runtime_id:payload.runtime_id,state_revision:payload.state_revision,quote_id:q.id,quote_revision:q.revision,client_id:clientId});let r;try{r=await request('/api/selections/'+lease.selection_id+'/what-if',assumptions);}finally{release(lease.selection_id);}if(selection!==held||held.expired)return;output.textContent=r.eligible?(r.display_value||r.value+' USD')+' · '+r.label:'Unavailable · '+r.reason;}catch(e){if(selection!==held)return;output.textContent=e.message;if(e.status===410){held.expired=true;checkSelection();}}finally{if(selection===held&&!held.expired)submit.disabled=false;}});root.append(form);}
async function pull(){if(snapshotBusy){snapshotAgain=true;return;}snapshotBusy=true;try{do{snapshotAgain=false;const next=await request('/api/current');if(next.schema!==schema||!['current','synthetic'].includes(next.mode))throw Error('Unsupported current payload');if(payload&&next.runtime_id===payload.runtime_id&&next.state_revision<=payload.state_revision)continue;payload=next;payloadTick=performance.now();applicablePeriods();draw();}while(snapshotAgain);}catch(e){connection='Reconnecting';$('flow').textContent='Current state unavailable · reconnecting';announce(e.message);}finally{snapshotBusy=false;}}
$('filters').addEventListener('submit',e=>e.preventDefault());for(const key of ['league','market','period','venue','search'])$(key).addEventListener(key==='search'?'input':'change',()=>{if(!payload)return;if(key==='league'||key==='market')applicablePeriods();draw();});$('filters').addEventListener('reset',()=>setTimeout(()=>{if(payload){applicablePeriods();draw();}},0));
document.addEventListener('keydown',e=>{if(!selection)return;if(e.key==='Escape'){e.preventDefault();closeDetails();return;}if(e.key==='Tab'&&matchMedia('(max-width:1050px)').matches){const nodes=[...$('details').querySelectorAll('button,summary,input,a')].filter(n=>!n.disabled&&!n.closest('[hidden]'));if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus();}}});
matchMedia('(max-width:1050px)').addEventListener('change',modal);
// Clean up a focused tombstone only after handback, never during a commit.
$('board').addEventListener('focusout',()=>setTimeout(()=>{if(payload&&$('board').querySelector('[data-removed]'))draw();},0));
const stream=new EventSource('/api/current/updates');stream.onopen=()=>{connection='Connected';if(payload)draw();pull();};stream.onerror=()=>{connection='Reconnecting';if(payload)draw();};stream.onmessage=e=>{try{const notice=JSON.parse(e.data);if(!notices.accept(notice))return;if(!payload||notice.runtime_id!==payload.runtime_id||notice.state_revision>payload.state_revision)pull();}catch(e){announce(e.message);}};
window.addEventListener('pagehide',()=>{stream.close();});
setInterval(()=>{if(!payload||!view)return;const elapsed=Math.floor((performance.now()-payloadTick)/1000);for(const ref of view.buttons.values())if(ref.button&&ref.q.age_seconds!==null)fillPrice(ref.button,{...ref.q,age_seconds:ref.q.age_seconds+elapsed},ref.quotes);},1000);modal();pull();

$('stop-current')?.addEventListener('click',async()=>{const button=$('stop-current');button.disabled=true;try{await request('/api/admin/current',{action:'stop'});announce('Updates stopped. Accounting preserved.');await pull();}catch(e){announce(e.message);}finally{button.disabled=false;}});
