'use strict';
// Authored simulated-DOM behavior. No owner startup, account state or network.
const assert=require('node:assert/strict'),fs=require('node:fs');
class Element{
  constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attributes={};this.style={};this._text='';this.className='';this.scrollTop=0;this.hidden=false;this.value='';this.id='';this.open=false;
    this.classList={add:(...names)=>{this.className=[...new Set([...this.className.split(' ').filter(Boolean),...names])].join(' ');},remove:(...names)=>{this.className=this.className.split(' ').filter(x=>!names.includes(x)).join(' ');},contains:name=>this.className.split(' ').includes(name),toggle:(name,yes)=>{if(yes??!this.classList.contains(name)){this.classList.add(name);return true;}this.classList.remove(name);return false;}};
  }
  set textContent(value){this._text=String(value);this.children=[];}
  get textContent(){return this._text+this.children.map(x=>x.textContent).join('');}
  get parentElement(){return this.parentNode||null;}
  append(...nodes){for(const node of nodes){node.remove();this.children.push(node);node.parentNode=this;}}
  replaceChildren(...nodes){for(const node of this.children)node.parentNode=null;this.children=[];this._text='';this.append(...nodes);}
  insertBefore(node,before){node.remove();const i=before?this.children.indexOf(before):this.children.length;this.children.splice(i<0?this.children.length:i,0,node);node.parentNode=this;}
  remove(){if(this.parentNode){const i=this.parentNode.children.indexOf(this);if(i>=0)this.parentNode.children.splice(i,1);}this.parentNode=null;}
  replaceWith(node){const parent=this.parentNode;if(parent){parent.insertBefore(node,this);this.remove();}}
  setAttribute(key,value){this.attributes[key]=String(value);}
  removeAttribute(key){delete this.attributes[key];}
  toggleAttribute(key,on){if(on)this.setAttribute(key,'');else this.removeAttribute(key);}
  matches(selector){if(selector.startsWith('#'))return this.id===selector.slice(1);if(selector.startsWith('.'))return this.classList.contains(selector.slice(1));if(selector==='details[open]')return this.tagName==='DETAILS'&&this.open;if(selector.startsWith('[data-')){const key=selector.slice(6,-1).replace(/-([a-z])/g,(_,x)=>x.toUpperCase());return this.dataset[key]!==undefined;}return this.tagName===selector.toUpperCase();}
  querySelectorAll(selectors){const parts=selectors.split(',');const result=[];const visit=node=>{for(const child of node.children){if(parts.some(x=>child.matches(x)))result.push(child);visit(child);}};visit(this);return result;}
  querySelector(selector){if(selector.startsWith('#')&&selector.includes(':'))throw new SyntaxError('Unescaped native identity is not a CSS selector');return this.querySelectorAll(selector)[0]||null;}
  focus(){document.activeElement=this;}
  contains(other){return other===this||this.children.some(x=>x.contains(other));}
  addEventListener(type,fn){this['on'+type]=fn;}
}
global.document={activeElement:null,body:new Element('body'),createElement:tag=>new Element(tag),getElementById:id=>{const find=node=>node.id===id?node:node.children.map(find).find(Boolean);return find(document.body);}};
const metric=(n,d='1',basis={})=>({eligible:true,exact:{numerator:String(n),denominator:String(d)},value:String(n),display_value:'+4.90%',estimate_class:'authored standalone hypothetical',basis:{conditioning:'conditional_decisive',probability_basis:'Pinnacle',size_basis:{common_capital_ceiling_usd:'100',native_quantity:'100'},fee_basis:'authored',...basis},details:{capital:{deployed_capital_usd:'44',residual_ceiling_usd:'56'},state_labels:{win:'Completed win',loss:'Completed loss'},state_costs:{win:{gross_return_usd:'100',settlement_fee_usd:'1',net_profit_usd:'55'},loss:{gross_return_usd:'0',settlement_fee_usd:'0',net_profit_usd:'-44'}}}});
const quote=(id,venue,side='YES',m=metric('700','143'))=>({id,revision:'authored:1',venue,state:'available',age_seconds:30,stale:false,source:{provider:'authored',native_side:side.toLowerCase(),native_outcome_id:'authored:'+side},display:{supported:true,american:'+138',cents:'42.0'},original:{value:'0.42',units:'usd_per_contract',payout:'1',payout_units:'USD'},times:{source_at:'2026-10-08T12:00:00Z',received_at:'2026-10-08T12:00:02Z'},rule_note:'Authored exact conditional meaning',provenance:{mode:'synthetic'},sharp_reference:{selected_odds:'2.10',odds:['2.10','1.80'],selected:0,source_at:['2026-10-08T12:00:00Z','2026-10-08T12:00:00Z']},calculations:{net_ev:m,ev:{eligible:false,reason:'Gross inputs unbound'},conservative:{eligible:false,reason:'Depth needed'}}});
(async()=>{
 const source=fs.readFileSync('app/dashboard/opportunity_static/current/comparison-board.js','utf8');
 const ui=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
 assert.equal(ui.reasonText('quote:authored:target_size_depth_insufficient'),'Available depth is below the comparison size');assert.equal(ui.reasonText('comparison_inputs_unbound'),'Comparison inputs are not bound for this quote');assert.equal(ui.reasonText('comparison_inputs_unbound; selection_binding_unverified'),'Comparison inputs are not bound for this quote; Event and selection binding is unverified');
 assert.equal(ui.american('2.10'),'+110');assert.equal(ui.american('1.80'),'−125');assert.equal(ui.american(null),'—');
 assert(ui.compareMetrics(metric('4895105001','1000000000'),metric('4895105000','1000000000'))<0);
 assert(ui.compareMetrics(metric('0'),metric('-1'))<0);assert(ui.compareMetrics({eligible:false,value:null},metric('0'))>0);
 assert.throws(()=>ui.metricExact({eligible:true,value:0}),/exact value/);assert.throws(()=>ui.rational(.5),/string/);
 const ordered=new ui.StableOrder(),a={id:'a',net_ev:metric('5')},b={id:'b',net_ev:metric('3')};
 assert.deepEqual(ordered.apply([b,a]).map(x=>x.id),['a','b']);
 b.net_ev=metric('6');assert.deepEqual(ordered.apply([a,b]).map(x=>x.id),['a','b']);assert.equal(ordered.pending,2);
 assert.deepEqual(ordered.apply([a,b],{resort:true}).map(x=>x.id),['b','a']);assert.equal(ordered.pending,0);
 const publicQuote=quote('public-retail','polymarket_us','Long',{eligible:false,reason:'public_retail_mandatory_settlement_and_other_charges_unqualified'});publicQuote.comparison_input_status={quantity:{status:'available_but_unbound',reason:'public_retail_historical_applicability_unqualified',public_retail:{observed_at:'2026-10-09T19:53:54Z',historical_applicability:false,metadata:{minimumTradeQty:'0.01',orderPriceMinTickSize:'0.0025',feeCoefficient:'0.0695',description:'Overtime included; tie pays $0.50'}}},fee:{status:'available_but_unbound',reason:'mandatory_costs_unqualified',public_entry_example:{quantity:'100',price:'0.2350',entry_fee_usd:'1.25'}}};const publicPane=new Element('section');document.body.append(publicPane);ui.renderDetails(publicPane,{quote:publicQuote},()=>{},()=>{});for(const label of ['Public retail metadata observation','0.01 / 0.01 contracts','$0.0025 per contract','Public entry fee example','$1.25','original price clock is unchanged','does not qualify net EV'])assert(publicPane.textContent.includes(label));
 delete publicQuote.sharp_reference;publicQuote.comparison_input_status.identity={status:'applicability_unresolved',reason:'source_local_occurrence_scope_unqualified',public_event:{event_id:'129629',market_id:'1083081',status:'available_and_bound',effective_until:'2026-10-09T21:08:03Z',selected:{native_key:['polymarket_us','129629','1083081','2165646','Long'],name:'Philadelphia Eagles',role:'away'},occurrence:{game_id:'19518',provider_game_id:'b635ddd1-4827-4593-ae8f-f41ae2f8914f',scheduled_start:'2026-10-11T13:30:00Z'},scope:{period:'full_game',selection_meaning:'selected_team_win',overtime:'included'},provenance:{response_finished_at:'2026-10-09T20:53:03Z'}}};ui.renderDetails(publicPane,{quote:publicQuote},()=>{},()=>{});for(const text of ['Public event membership observation','Event 129629 contains market 1083081','2165646 / Long','Philadelphia Eagles · away','Game 19518','Historical applicability unqualified','Pinnacle opposition remain unqualified'])assert(publicPane.textContent.includes(text));assert(!publicPane.textContent.includes('exceeded its response limit'));publicQuote.comparison_input_status.identity.public_event.status='expired';ui.renderDetails(publicPane,{quote:publicQuote},()=>{},()=>{});assert(publicPane.textContent.includes('Outside the metadata interval'));
 const qa=quote('kalshi-one','kalshi'),qb=quote('novig-one','novig','',metric('6'));
 const nestedReference=quote('nested-reference','kalshi');delete nestedReference.sharp_reference;nestedReference.calculations.net_ev={...metric('5'),details:{natural:{details:{reference:{selected_odds:'2.10',opposing_odds:'1.80'}}}}};assert.equal(ui.referenceOf(nestedReference).selected_odds,'2.10');
 const grossFallback=quote('gross-fallback','kalshi');grossFallback.calculations.net_ev.details.gross_decisive_benchmark={eligible:true,display_value:'+75.00%'};assert.equal(ui.grossMetric(grossFallback).display_value,'+75.00%');grossFallback.calculations.ev={eligible:true,display_value:'+42.00%'};assert.equal(ui.grossMetric(grossFallback).display_value,'+42.00%');grossFallback.calculations.ev={eligible:false,reason:'Legacy unbound'};assert.equal(ui.readableState({},'completed:0:0'),'Unknown state');assert.equal(ui.readableState({'completed:0:0':'completed:0:0'},'completed:0:0'),'Unknown state');
 assert.equal(ui.bestMetric({kalshi:qa,novig:qb}).selected_venue,'novig');
 assert.equal(ui.bestMetric({kalshi:qa,novig:qb},'kalshi').selected_quote_id,'kalshi-one');
 qb.calculations.net_ev=metric('6','1',{conditioning:'complete'});assert.equal(ui.bestMetric({kalshi:qa,novig:qb}).eligible,false);
 qb.calculations.net_ev=metric('6');
 const dallas=quote('dallas-short','polymarket_us','SHORT'),no=quote('dallas-no','kalshi','NO',{eligible:false,reason:'Fee applicability unknown'});
 assert.equal(ui.bestMetric({kalshi:no}).reason,'Fee applicability unknown');assert.equal(ui.metricText(ui.bestMetric({kalshi:no})),'— Fee needed');
 const groups=[{id:'winner-one',market:'winner',period:'full_game',period_boundary:'authored_full_game_including_ot',line:null,anchor_participant:null,outcomes:[{id:'toronto',label:'Toronto wins',participant:'toronto',predicate:'win',signed_line:null,quotes:{kalshi:qa,novig:qb},alternatives:{}},{id:'dallas',label:'Dallas wins',participant:'dallas',predicate:'win',signed_line:null,quotes:{polymarket_us:dallas},alternatives:{}}]},
 {id:'winner-two',market:'winner',period:'full_game',period_boundary:'authored_full_game_including_ot',line:null,anchor_participant:null,outcomes:[{id:'dallas-no-outcome',label:'Dallas does not win',participant:'dallas',predicate:'not_win',signed_line:null,quotes:{kalshi:no},alternatives:{}}]}];
 const payload={mode:'synthetic',source_status:{prophetx:{state:'error'}},events:[{id:'authored-game',title:'Toronto — Boston / authored Dallas meanings',league:'NHL',start_at:'2026-10-08T20:15:00Z',groups}]};
 assert.equal(ui.canonicalGroups(payload.events[0]).length,1);
 const board=new Element('section');document.body.append(board);let chosen;
 const f={league:'',market:'winner',period:'full_game',venue:'',search:''};
 const rendered=ui.reconcileBoard(board,payload,f,row=>chosen=row,null);
 assert.deepEqual(board.querySelector('thead').querySelectorAll('th').map(x=>x.textContent),['Selection','Kalshi','Polymarket US','Novig','ProphetX','Pinnacle','Est. net EV']);
 assert.equal(rendered.rows,3);assert(board.textContent.includes('+110'));assert(board.textContent.includes('SHORT'));assert(board.textContent.includes('Other native contracts'));
 assert(!board.textContent.includes('Fee neededFee needed'));assert(board.textContent.includes('Fee needed'));assert(board.textContent.includes('Inspect Details'));assert(!board.textContent.includes('42.0c'));assert(board.textContent.includes('Source failed'));
 const button=rendered.buttons.get('dallas-short').button;button.focus();ui.reconcileBoard(board,payload,f,row=>chosen=row,'dallas-short');assert.equal(document.activeElement,button);button.onclick();assert.equal(chosen.quote.source.native_side,'short');
 const fold=board.querySelector('details');fold.open=true;ui.reconcileBoard(board,payload,f,row=>chosen=row,null);assert.equal(board.querySelector('details').open,true);
 const pane=new Element('aside');document.body.append(pane);ui.renderDetails(pane,chosen,()=>{},null,{ceiling:'100',onSize:()=>{}});
 const nativeTrigger=new Element('button');nativeTrigger.id='net-outcome:authored-native-id';document.body.append(nativeTrigger);nativeTrigger.focus();assert.doesNotThrow(()=>ui.renderDetails(pane,chosen,()=>{},null,{ceiling:'100',onSize:()=>{}}));assert.equal(document.activeElement,nativeTrigger);
 assert.equal(ui.reasonText('retained_pinnacle_candidate_occurrence_edge_unqualified'),'Retained NFL Pinnacle prices exist, but the exact provider-to-game link and quote applicability are unqualified');
 assert(pane.textContent.includes('Selected bet and native meaning'));assert(pane.textContent.includes('Pinnacle reference'));assert(pane.textContent.includes('+110 · original 2.10'));assert(pane.textContent.includes('−125 · original 1.80'));
 const boundReview=structuredClone(chosen);boundReview.quote.comparison_input_status={identity:{status:'available_and_bound',reason:'identity_source_inputs_bound',public_event:{event_id:'129629',market_id:'1083081'}},reference:{status:'available_and_bound',reason:'original_pinnacle_opposition_bound',prospective_review:{effective_from:'2026-10-09T21:55:06Z',effective_until:'2026-10-10T21:55:06Z',venue:'Tottenham',rules:'Tie void differs from native0.50',rule_version:'Prospective only'}}};
 ui.renderDetails(pane,boundReview,()=>{},null,{});assert(pane.textContent.includes('Separate prospective occurrence review'));assert(pane.textContent.includes('2026-10-09T21:55:06Z'));assert(pane.textContent.includes('Exact Pinnacle opposition is attached to this observation'));assert(!pane.textContent.includes('Exact cross-source occurrence and Pinnacle opposition remain unqualified'));assert(pane.textContent.includes('Tie and exceptional mass, costs and execution depth remain separate'));
 ui.renderDetails(pane,chosen,()=>{},null,{ceiling:'100',onSize:()=>{}});
 const input=pane.querySelector('#comparison-ceiling');input.value='175';input.focus();pane.scrollTop=71;ui.renderDetails(pane,chosen,()=>{},null,{ceiling:'100',onSize:()=>{}});
 assert.equal(pane.querySelector('#comparison-ceiling').value,'175');assert.equal(document.activeElement.id,'comparison-ceiling');assert.equal(pane.scrollTop,71);
 ui.renderDetails(pane,{...chosen,expired:true},()=>{},null,{ceiling:'100',onSize:()=>{}});assert(pane.textContent.includes('No longer available'));assert(pane.querySelector('#selection-notice').hidden===false);
 grossFallback.calculations.net_ev.details.state_labels={'completed:0:0':'Tie after the completed game'};grossFallback.calculations.net_ev.details.state_costs={'completed:0:0':{gross_return_usd:'50',settlement_fee_usd:'0',net_profit_usd:'9'}};ui.renderDetails(pane,{...chosen,quote:grossFallback},()=>{},null,{});assert(pane.textContent.includes('Gross decisive benchmark: +75.00%'));assert(pane.querySelector('table').textContent.includes('Tie after the completed game'));assert(!pane.querySelector('table').textContent.includes('completed:0:0'));assert(pane.querySelector('pre').textContent.includes('completed:0:0'));
 const attack=quote('unsafe-id','kalshi');attack.display.american='<img src=x onerror=alert(1)>';const safe=new Element('button');ui.fillPrice(safe,attack);assert(safe.textContent.includes('<img'));assert.equal(safe.querySelectorAll('img').length,0);
 const cell={configured:true,checked:true,status:'offerings_returned',counts:{admitted_quotes:4,displayed_quotes:4,filtered_quotes:0,unresolved_mapping_quotes:0}};
 assert(ui.coverageDescription({...cell,configured:false}).includes('Not configured'));
 assert(ui.coverageDescription({...cell,status:'no_offerings_returned'}).includes('Checked empty'));
 assert(ui.coverageDescription({...cell,status:'failed_source'}).includes('Source failed'));
 assert(ui.coverageDescription({...cell,display_reason:'filtered_out'}).includes('Filtered'));
 assert(ui.coverageDescription({...cell,counts:{...cell.counts,unresolved_mapping_quotes:2}}).includes('Mapping needed'));
 const controller=fs.readFileSync('app/dashboard/opportunity_static/current/comparison-view.js','utf8');assert(controller.includes('/api/comparison'));assert(controller.includes('/api/coverage'));assert(!/https?:\/\//.test(controller));
 // Exercise the real view controller against one authored read-only response.
 document.body=new Element('body');document.body.dataset.view='ev';document.addEventListener=()=>{};
 global.window={addEventListener:()=>{}};global.matchMedia=()=>({matches:false});
 class Stream{constructor(url){this.url=url;Stream.last=this;}close(){}}
 global.EventSource=Stream;const reads=[];
 for(const id of ['filters','league','market','venue','search','results','basis','rankings','details','flow','resort','limits','test-notice','announcement','stop-current']){const n=new Element(['filters'].includes(id)?'form':['rankings','details'].includes(id)?'section':'div');n.id=id;document.body.append(n);}
 document.getElementById('results').value='all';
 const row=(id,n)=>({id,quote_revision:'authored:1',event_id:'event',group_id:'group',outcome_id:'selection-'+id,title:'Authored Toronto — Boston',league:'NHL',market:'winner',period:'full_game',period_boundary:'authored full game',selection:'Selection '+id,venue:'kalshi',venue_odds:'+138',reference_odds:'2.10',basis_id:'same-basis',net_ev:metric(n),gross:{eligible:true,display_value:'+75.00%'},quote:quote(id,'kalshi'),conservative:{eligible:false,reason:'Depth needed'}});
 let latest={schema:'comparison-metrics-1',runtime_id:'authored-ui',state_revision:1,mode:'synthetic',rows:[row('a','5'),row('b','3')],pairs:[],groups:[{basis_id:'same-basis',rows:[row('a','5'),row('b','3')]}],limits:{candidate_pairs:256,allocation_evaluations:1024,returned_results:128}};
 global.fetch=async url=>{reads.push(String(url));return{ok:true,json:async()=>latest};};
 const helperURL='data:text/javascript;base64,'+Buffer.from(source).toString('base64');
 await import('data:text/javascript;base64,'+Buffer.from(controller.replace("'./comparison-board.js'",JSON.stringify(helperURL))).toString('base64'));
 const settle=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};await settle();
 const ranking=document.getElementById('rankings');assert.deepEqual(ranking.children.map(n=>n.dataset.id),['a','b']);
 assert(ranking.textContent.includes('Gross decisive benchmark: +75.00%'));
 const stableButton=document.getElementById('inspect-a');stableButton.focus();latest={...latest,state_revision:2,rows:[row('b','6'),row('a','5')]};Stream.last.onmessage();await settle();
 assert.deepEqual(ranking.children.map(n=>n.dataset.id),['a','b']);assert.equal(document.activeElement,stableButton);assert(document.getElementById('resort').textContent.includes('2 updates'));
 document.getElementById('resort').onclick();assert.deepEqual(ranking.children.map(n=>n.dataset.id),['b','a']);
 stableButton.onclick();assert(document.getElementById('details').textContent.includes('Selection a'));
 latest={...latest,state_revision:3,rows:[row('b','6')]};Stream.last.onmessage();await settle();
 assert(document.getElementById('details').textContent.includes('No longer available'));assert(document.getElementById('details').textContent.includes('Selection a'));
 assert(reads.every(url=>url.startsWith('/api/comparison?')));assert.equal(Stream.last.url,'/api/current/updates');
 // Pair cards use canonical labels, exact category ranking and the sanitized
 // S05 fee summary; both leg revisions update together on the same pair ID.
 document.body=new Element('body');document.body.dataset.view='arbs';
 for(const id of ['filters','league','market','venue','search','results','basis','rankings','details','flow','resort','limits','test-notice','announcement','stop-current']){const n=new Element(id==='filters'?'form':['rankings','details'].includes(id)?'section':'div');n.id=id;document.body.append(n);}
 document.getElementById('results').value='all';
 const stateLabels={'completed:0:0':'Tie after the completed game','completed:1:2':'Dallas wins the completed game',noncompleted:'Game did not complete'};
 const pair=(id,value,category='conditional_known_states',revision='leg-r1')=>({id,title:'Authored Dallas — Tampa Bay',league:'NFL',market:'winner',category,truncated:true,state_labels:stateLabels,limiting_states:['completed:0:0'],limiting_state_labels:['Tie after the completed game'],buffered_minimum_return:{...metric(value),display_value:'+3.09%'},legs:[{selection:'Dallas wins',venue:'kalshi',odds:'+150',quantity:'100',native_side:'yes',revision},{selection:'Tampa Bay wins',venue:'polymarket_us',odds:'+150',quantity:'100',native_side:'long',revision}],details:{minimum_return_usd:'3',denominator_usd:'97',native_quantities:['100','100'],state_labels:stateLabels,unknown_states:['noncompleted'],state_profits_usd:{'completed:1:2':'3','completed:0:0':'3',noncompleted:null},depth:{depth_qualified:true},one_leg_exposures:[{deployed_capital_usd:'44',state_profits_usd:{'completed:0:0':'9'}},{deployed_capital_usd:'53'}],cost_summaries:{base:[{acquisition_usd:'40'},{acquisition_usd:'50'}],conservative:[{acquisition_usd:'41',entry_fee_usd:'0.1',rounding_refund_usd:'0',net_entry_fee_usd:'0.1',states:{'completed:1:2':{gross_return_usd:'100',settlement_fee_usd:'1',net_profit_usd:'58.9'},noncompleted:{gross_return_usd:null,settlement_fee_usd:null,net_profit_usd:null}}},{acquisition_usd:'51',entry_fee_usd:'0',rounding_refund_usd:'0',net_entry_fee_usd:'0',states:{}}]}}});
 const missingLabelPair=pair('p2','4');missingLabelPair.state_labels={};missingLabelPair.details.state_labels={};missingLabelPair.limiting_state_labels=['completed:0:0'];
 latest={schema:'comparison-metrics-1',runtime_id:'authored-pairs',state_revision:1,mode:'synthetic',rows:[],groups:[],pairs:[pair('p1','300','conditional_known_states'),missingLabelPair,pair('complete','10','all_modeled_outcomes')],limits:{candidate_pairs:256,allocation_evaluations:1024,returned_results:128}};
 await import('data:text/javascript;base64,'+Buffer.from(controller.replace("'./comparison-board.js'",JSON.stringify(helperURL))+'\n// Authored Arbs controller fixture').toString('base64'));await settle();
 assert(document.getElementById('basis').querySelectorAll('option').some(n=>n.value==='all_modeled_outcomes'));assert.deepEqual(document.getElementById('rankings').children.map(n=>n.dataset.id),['p1','p2']);
 assert(document.getElementById('rankings').textContent.includes('limiting state Tie after the completed game'));assert(!document.getElementById('rankings').textContent.includes('completed:0:0'));assert(document.getElementById('inspect-p2').textContent.includes('limiting state Unknown state'));
 document.getElementById('inspect-p1').onclick();assert(document.getElementById('details').textContent.includes('Dallas wins'));assert(document.getElementById('details').textContent.includes('Tampa Bay wins'));assert(document.getElementById('details').textContent.includes('leg-r1'));assert(document.getElementById('details').textContent.includes('Entry fee: $0.1'));assert(document.getElementById('details').textContent.includes('Unknown'));assert(document.getElementById('details').textContent.includes('partial search'));
 const visibleTables=document.getElementById('details').querySelectorAll('table').map(n=>n.textContent).join(' ');assert(visibleTables.includes('Tie after the completed game'));assert(visibleTables.includes('Dallas wins the completed game'));assert(visibleTables.includes('Game did not complete'));assert(!visibleTables.includes('completed:0:0'));assert(document.getElementById('details').querySelectorAll('pre').at(-1).textContent.includes('completed:0:0'));
 latest={...latest,state_revision:2,pairs:[pair('p1','2','conditional_known_states','leg-r2'),pair('p2','4')]};Stream.last.onmessage();await settle();assert(document.getElementById('details').textContent.includes('leg-r2'));assert(!document.getElementById('details').textContent.includes('leg-r1'));assert.deepEqual(document.getElementById('rankings').children.map(n=>n.dataset.id),['p1','p2']);
 latest={...latest,state_revision:3,pairs:[pair('p2','4')]};Stream.last.onmessage();await settle();assert(document.getElementById('details').textContent.includes('No longer available'));assert(document.getElementById('details').textContent.includes('Dallas wins'));
 const freshPublic=structuredClone(publicQuote);freshPublic.comparison_input_status.quantity.status='available_and_bound';Object.assign(freshPublic.comparison_input_status.quantity.public_retail,{retained_observation_bound:true,quote_revision:2,effective_from:'2026-10-09T22:43:06.160459Z',effective_until:'2026-10-09T22:58:06.160459Z',metadata_receipt:{url:'https://gateway.polymarket.us/v1/events?id=129629&limit=1'}});freshPublic.comparison_input_status.fee.charge_completeness=JSON.parse(fs.readFileSync(__dirname+'/../app/fixtures/comparison-retail-charge-audit-v1.json','utf8'));const freshPane=new Element('section');document.body.append(freshPane);ui.renderDetails(freshPane,{quote:freshPublic},()=>{},()=>{});assert(freshPane.textContent.includes('Bound to exact retained Long revision 2'));assert(freshPane.textContent.includes('no live freshness claim'));assert(freshPane.textContent.includes('Settlement and other mandatory charges unknown'));assert(freshPane.textContent.includes('Mandatory charge completeness'));assert(freshPane.textContent.includes('no current clearing fees'));assert(freshPane.textContent.includes('Standard direct-site retail selected; total published transaction costs remain unqualified'));assert(freshPane.textContent.includes('no cost profile, net EV or renewed review interval'));freshPublic.comparison_input_status.fee.direct_site_case=JSON.parse(fs.readFileSync(__dirname+'/../app/fixtures/comparison-direct-site-retail-v1.json','utf8'));freshPublic.calculations.direct_site_estimate={eligible:true,display_value:'-1.30 %',quantity:'404.04',price:'0.2350',ceiling_usd:'100',acquisition_usd:'94.9494',entry_fee_usd:'5.05',deployed_usd:'99.9994',independent_gates:['actual tie/exceptional probability mass','complete payout equivalence','execution phase and executable depth'],evaluation_at:'2026-10-09T22:43:09.353065Z'};ui.renderDetails(freshPane,{quote:freshPublic},()=>{},()=>{});assert(freshPane.textContent.includes('Standard direct-site retail costs'));assert(freshPane.textContent.includes('Modeled conditional after-cost EV'));assert(freshPane.textContent.includes('-1.30 %'));assert(freshPane.textContent.includes('404.04 contracts'));assert(freshPane.textContent.includes('modeled, not verified'));assert(!freshPane.textContent.includes('Participant / channel'));assert(!freshPane.textContent.includes('Required evidence'));freshPublic.comparison_input_status.quantity.status='expired';ui.renderDetails(freshPane,{quote:freshPublic},()=>{},()=>{});assert(freshPane.textContent.includes('outside its interval'));
 assert.equal(ui.reasonText('execution_channel_and_mandatory_charges_unqualified'),'Standard direct-site retail: published mandatory transaction charges need qualification');
 // Coverage rendering preserves distinct observation stages and exact nulls.
 document.body=new Element('body');document.body.dataset.view='coverage';
 for(const id of ['filters','league','market','venue','coverage','reference-coverage','details','flow','test-notice','announcement','stop-current']){const n=new Element(id==='filters'?'form':'section');n.id=id;document.body.append(n);}
 const observed=(sport,venue,patch={})=>({sport,venue,configured:true,checked:true,status:'offerings_returned',latest:{checked_at:'2026-10-08T12:00:05Z',offered:{markets:1},source_clocks:['2026-10-08T12:00:00Z']},counts:{admitted_quotes:0,displayed_quotes:0,filtered_quotes:0,unresolved_mapping_quotes:0,rejected_markets:0,rejected_quotes:null},...patch});
 latest={schema:'comparison-coverage-1',mode:'synthetic',totals:{admitted_quotes:6,displayed_quotes:5,filtered_quotes:1},cells:[observed('NFL','kalshi',{counts:{...cell.counts,admitted_quotes:4,displayed_quotes:4,rejected_markets:0,rejected_quotes:null}}),observed('NCAAB','novig',{status:'no_offerings_returned',latest:{checked_at:'2026-10-08T12:00:05Z',offered:{markets:0}}}),observed('NFL','polymarket_us',{status:'failed_source',latest:{checked_at:'2026-10-08T12:00:05Z',offered:{markets:null}}}),observed('NHL','prophetx',{display_reason:'filtered_out',counts:{...cell.counts,admitted_quotes:2,displayed_quotes:1,filtered_quotes:1,rejected_markets:0,rejected_quotes:null}}),observed('NBA','prophetx',{configured:false,checked:false}),observed('NHL','pinnacle')]};
 const beforeCoverageReads=reads.length;await import('data:text/javascript;base64,'+Buffer.from(controller.replace("'./comparison-board.js'",JSON.stringify(helperURL))+'\n// Authored Coverage controller fixture').toString('base64'));await settle();
 assert.equal(document.getElementById('flow').textContent,'5 displayed / 6 admitted · 1 filtered');const coverageText=document.getElementById('coverage').textContent;for(const text of ['Checked empty','Source failed','Filtered','Not configured for this sport','rejected quotes: Unknown','Last check:','quote freshness uses original price clocks'])assert(coverageText.includes(text));assert(!document.getElementById('test-notice').hidden);assert(document.getElementById('reference-coverage').textContent.includes('offered reference markets 1'));assert(reads.slice(beforeCoverageReads).every(url=>url.startsWith('/api/coverage?')));
 // The production Odds controller applies optional-size metrics only to the
 // exact current quote revision and retires a selected price without switching.
 document.body=new Element('body');if(!global.crypto)Object.defineProperty(global,'crypto',{value:require('node:crypto').webcrypto});global.setInterval=()=>0;global.matchMedia=()=>({matches:false,addEventListener:()=>{}});
 for(const id of ['filters','league','market','period','venue','search','board','details','count','flow','test-notice','announcement','source-updates','size-note','stop-current']){const n=new Element(id==='filters'?'form':['board','details'].includes(id)?'section':'div');n.id=id;document.body.append(n);}
 document.getElementById('period').value='full_game';document.getElementById('market').value='winner';
 let current={...structuredClone(payload),schema:'predict-current-1',runtime_id:'authored-odds',state_revision:1,state:'available',clock_at:'2026-10-08T12:00:30Z'};
 let sizeResponse={schema:'comparison-metrics-1',runtime_id:'authored-odds',state_revision:1,rows:[{id:'kalshi-one',quote_revision:'authored:1',net_ev:{...metric('7'),display_value:'+7.00%'},conservative:{eligible:false,reason:'Depth needed'}}]},sizeFailed=false;const oddsReads=[];
 global.fetch=async url=>{oddsReads.push(String(url));return String(url).startsWith('/api/comparison?')?{ok:!sizeFailed,json:async()=>sizeFailed?{reason:'Authored size failure'}:structuredClone(sizeResponse)}:{ok:true,json:async()=>structuredClone(current)};};
 const clientURL='data:text/javascript;base64,'+Buffer.from(fs.readFileSync('app/dashboard/opportunity_static/current/current-client.js','utf8')).toString('base64');
 const oddsController=fs.readFileSync('app/dashboard/opportunity_static/current/current.js','utf8').replace("'./current-client.js'",JSON.stringify(clientURL)).replace("'./comparison-board.js'",JSON.stringify(helperURL));
 await import('data:text/javascript;base64,'+Buffer.from(oddsController).toString('base64'));await settle();
 document.getElementById('board').querySelectorAll('[data-quote-id]').find(n=>n.dataset.quoteId==='kalshi-one').onclick();
 let sizeInput=document.getElementById('comparison-ceiling');sizeInput.value='175';sizeInput.focus();document.getElementById('details').querySelector('form').onsubmit({preventDefault(){}});await settle();
 assert(document.getElementById('details').textContent.includes('+7.00%'));assert.equal(document.activeElement.id,'comparison-ceiling');assert(oddsReads.some(url=>url==='/api/comparison?ceiling=175'));
 sizeResponse.rows[0].quote_revision='wrong-revision';sizeInput=document.getElementById('comparison-ceiling');sizeInput.value='176';document.getElementById('details').querySelector('form').onsubmit({preventDefault(){}});await settle();assert(document.getElementById('details').textContent.includes('same current input revision'));assert(!document.getElementById('details').textContent.includes('+7.00%'));
 sizeFailed=true;document.getElementById('comparison-ceiling').value='177';document.getElementById('details').querySelector('form').onsubmit({preventDefault(){}});await settle();assert(document.getElementById('details').textContent.includes('Authored size failure'));assert(document.getElementById('board').textContent.includes('+138'));
 current={...current,state_revision:2,events:[]};Stream.last.onmessage({data:JSON.stringify({schema:'predict-current-1',runtime_id:'authored-odds',state_revision:2})});await settle();assert(document.getElementById('details').textContent.includes('No longer available'));assert(document.getElementById('details').textContent.includes('Toronto wins'));assert(!document.getElementById('details').textContent.includes('+7.00%'));
 assert(oddsReads.every(url=>url.startsWith('/api/current')||url.startsWith('/api/comparison?')));
 console.log('PASS comparison UI: exact signed sorting, comparable row-best venue, stable Re-sort, American reference odds, compact NO/SHORT meaning, preserved Details focus/size/retirement, escaped text and distinct coverage states (authored simulated DOM).');
})().catch(error=>{console.error(error);process.exitCode=1;});
