const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const source=fs.readFileSync('app/dashboard/opportunity_static/current/current-client.js','utf8');const {ReviewRequests,NoticeGate}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const schema='predict-current-1',gate=new NoticeGate(schema),notice=(runtime,revision)=>({schema,runtime_id:runtime,state_revision:revision});
assert(gate.accept(notice('a',2)));assert(!gate.accept(notice('a',2)));assert(!gate.accept(notice('a',1)));assert(gate.accept(notice('a',3)));assert(gate.accept(notice('b',1)));assert.throws(()=>gate.accept({...notice('b',2),schema:'bad'}));
const releases=[],calls=[],display=[],errors=[];let resolve,reject;
const manager=new ReviewRequests(request=>{calls.push(request);return new Promise((a,b)=>{resolve=a;reject=b;});},id=>releases.push(id));
let a=manager.replace('old',r=>display.push(r.selection_id),e=>errors.push(e));await new Promise(setImmediate);assert.deepEqual(calls,['old']);
let b=manager.replace('new',r=>display.push(r.selection_id),e=>errors.push(e));resolve({selection_id:'old'});await a;await new Promise(setImmediate);assert.deepEqual(releases,['old']);assert.deepEqual(calls,['old','new']);resolve({selection_id:'new'});await b;assert.deepEqual(display,['new']);
let c=manager.replace('adoption',r=>display.push(r.selection_id),e=>errors.push(e.message));await new Promise(setImmediate);reject(Error('selection_changed'));await c;assert.deepEqual(display,['new']);assert.deepEqual(errors,['selection_changed']);
let d=manager.replace('expired',r=>display.push(r.selection_id),e=>errors.push(e));await new Promise(setImmediate);manager.invalidate();resolve({selection_id:'expired'});await d;assert.deepEqual(display,['new']);assert.deepEqual(releases,['old','expired']);
let e=manager.replace('superseded-before-send',r=>display.push(r.selection_id),e=>errors.push(e));manager.invalidate();await e;assert(!calls.includes('superseded-before-send'));
console.log('Current client: duplicate/out-of-order notices, runtime changes, serialized replacement, failed adoption and expired late responses pass');})().catch(e=>{console.error(e);process.exitCode=1;});
