'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const names=['kalshi-events','kalshi-markets','us-events','us-markets','sports','markets','events','limit','refresh','stale','requests','credits','response','storage','used','remaining','enabled','state','bindings'];
const fields=Object.fromEntries(names.map(n=>['sources-'+n,{value:'',checked:false}]));
const saved={sports:'NFL',markets:'h2h',events:'mock',limit:'2',refresh:'60',stale:'120',requests:'12',credits:'12',response:'1048576',storage:'8388608',enabled:true,used:'999',remaining:'999',auto_start:true};
let stored;
const ctx={document:{getElementById:k=>fields[k]},localStorage:{getItem:()=>JSON.stringify(saved),setItem:(k,v)=>{stored=JSON.parse(v)}},Date};ctx.globalThis=ctx;
vm.runInNewContext(fs.readFileSync('app/dashboard/opportunity_static/source-settings.js','utf8'),ctx);
assert.equal(fields['sources-enabled'].checked,false);assert.equal(fields['sources-used'].value,'');
assert.equal(ctx.PredictSources.settings({source_settings_available:true}),null);
fields['sources-enabled'].checked=true;
assert.throws(()=>ctx.PredictSources.settings({source_settings_available:true}),/fresh mock quota/);
fields['sources-used'].value='0';fields['sources-remaining'].value='100';
const settings=ctx.PredictSources.settings({source_settings_available:true});
assert.equal(settings.correspondence_policy,'source-correspondence-1');
assert.equal(settings.native_scopes.kalshi,'required-63-v1');assert.equal(settings.native_scopes.polymarket_us,'required-63-v1');
assert.equal(settings.roles.pinnacle,'reference');assert.equal(settings.roles.novig,'aggregate_comparison');assert(!('auto_start' in stored));assert(!('remaining' in stored));assert(!('enabled' in stored));
ctx.PredictSources.render({active:true,source_settings_available:true});assert.equal(fields['sources-used'].value,'');assert(fields['sources-enabled'].disabled);
ctx.PredictSources.render({active:false,source_settings_available:true,aggregate:{state:'waiting',accounting:{requests:2,reserved_credits:6,conservative_remaining:94}}});assert(fields['sources-state'].textContent.startsWith('stopped'));
ctx.PredictSources.render({active:false,source_settings_available:true},'saved/session');
assert.equal(fields['sources-bindings'].href,'/api/source-bindings?download=true&capture=saved%2Fsession');
console.log('Inert settings, role isolation, fresh quota and stopped status pass');
