// Reusable consumer of predict-current-1. No provider requests or source ownership.
export const venues = {kalshi:'Kalshi',polymarket_us:'Polymarket US',novig:'Novig',prophetx:'ProphetX'};
export const periods = {full_game:'Full game',first_half:'First half',period_1:'1st period'};
export const markets = {winner:'Winner',spread:'Spread',total:'Total'};
export function el(tag, text, cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
// Exact rational originals for gross comparisons. Display decimals are never inputs.
function rational(s){const m=/^([+-]?)(?:(\d+)(?:\.(\d*))?|\.(\d+))(?:[eE]([+-]?\d+))?$/.exec(s);if(!m||s.length>256)throw Error('Invalid original');const frac=m[3]??m[4]??'',exponent=Number(m[5]||0);if(Math.abs(exponent)>256)throw Error('Original exponent outside bounds');const n=BigInt((m[1]==='-'?'-':'')+(m[2]||'0')+frac),power=frac.length-exponent;return power>=0?[n,10n**BigInt(power)]:[n*10n**BigInt(-power),1n];}
export function price(q){let [n,d]=rational(q.original.value);if(q.original.units==='decimal_odds')return [d,n];if(q.original.units==='cents_per_contract')return [n,d*100n];return [n,d];}
export function compare(a,b){const [an,ad]=price(a),[bn,bd]=price(b);const v=an*bd-bn*ad;return v<0n?-1:v>0n?1:0;}
export function eligible(q){return q&&q.comparison.eligible&&q.state==='available'&&!q.stale&&q.display.supported;}
export function cue(q, quotes){if(q.comparison.contexts){const key=Object.keys(venues).filter(v=>Object.hasOwn(quotes,v)).join('+');return q.comparison.contexts[key]?.cue||'';}const list=Object.values(quotes).filter(eligible);if(!eligible(q)||list.length<2)return '';const best=list.reduce((a,b)=>compare(a,b)<=0?a:b);if(compare(q,best)!==0)return '';return list.filter(x=>compare(x,best)===0).length>1?'Tied quote':'Better quote';}
export function rawGap(q,quotes){if(q.comparison.contexts){const key=Object.keys(venues).filter(v=>Object.hasOwn(quotes,v)).join('+');const r=q.comparison.contexts[key]?.raw_difference;if(!r?.eligible)return null;return r.display_value;}const other=Object.values(quotes).filter(x=>eligible(x)&&x.id!==q.id);if(!eligible(q)||!other.length)return null;const best=other.reduce((a,b)=>compare(a,b)<=0?a:b);const [an,ad]=price(q),[bn,bd]=price(best);const n=(bn*ad-an*bd)*1000n,d=ad*bd;const neg=n<0n;const abs=neg?-n:n;const rounded=(abs*2n+d)/(2n*d);return (neg?'-':rounded>0n?'+':'')+String(rounded/10n)+'.'+String(rounded%10n)+'c';}
export function age(q){if(q.book_confirmation)return 'Book confirmed '+(q.confirmation_age_seconds===null?'unknown age':Math.floor(q.confirmation_age_seconds)+'s ago');if(q.times.source_at===null)return 'Source age unknown';const s=q.age_seconds;if(s===null)return 'Source age unknown';return s<60?s+'s ago':s<3600?Math.floor(s/60)+'m ago':Math.floor(s/3600)+'h ago';}
export function quoteText(q){if(!q.display.supported)return 'Conversion unavailable';return q.display.american+' · '+q.display.cents+'c'+(q.display.equivalent?' eq':'');}
export function fillPrice(button,q,quotes){button.replaceChildren();button.classList.remove('better');if(!q.display.supported){button.append(el('span','Conversion unavailable','unavailable'),el('span',q.display.reason||'Unsupported quote basis','age'));button.setAttribute('aria-label',venues[q.venue]+', conversion unavailable, inspect original quote in Details');return;}button.append(el('span',q.display.american,'american'),el('span',q.display.cents+'c'+(q.display.equivalent?' eq':''),'cents'));button.append(el('span',age(q)+(q.source.provider==='the_odds_api'?' · Delayed · Freshness unqualified':q.stale?' · Stale':q.state==='budget_delayed'?' · Delayed':''),'age'));const c=cue(q,quotes);if(c){button.append(el('span',c,'cue'));if(c==='Better quote')button.classList.add('better');}if(q.rules_differ===true||(q.provenance.mode==='synthetic'&&q.venue==='polymarket_us'))button.append(el('span','Rules differ','rules'));if(button.classList.contains('alternative'))button.prepend(el('span','Alternative · '+q.source.native_side,'age'));button.setAttribute('aria-label',venues[q.venue]+', '+quoteText(q)+', '+age(q)+', '+(c||'quote')+(q.stale?', stale':'')+', inspect Details');}
export function filteredEvents(payload,filters){return payload.events.map(e=>({...e,groups:e.groups.filter(g=>(!filters.market||g.market===filters.market)&&g.period===filters.period)})).filter(e=>(!filters.league||e.league===filters.league)&&e.title.toLocaleLowerCase().includes(filters.search.toLocaleLowerCase())&&e.groups.length);}
export function renderBoard(root,payload,filters,onSelect,selectedId){root.replaceChildren();const events=filteredEvents(payload,filters);const buttons=new Map();let rows=0;
for(const e of events){const section=el('article',undefined,'event');section.dataset.event=e.id;const head=el('div',undefined,'event-head');const title=el('div');title.append(el('h2',e.title),el('p',new Date(e.start_at).toLocaleString('en-US',{timeZone:'America/New_York',weekday:'short',hour:'numeric',minute:'2-digit'})+' ET'+(payload.mode==='synthetic'?' · Synthetic schedule':'')));head.append(title,el('span',e.league,'league-tag'));section.append(head);
for(const g of e.groups){const groupTitle=el('div',(periods[g.period]||g.period.replaceAll('_',' '))+' · '+markets[g.market]+(g.line?' · '+(g.market==='spread'?(e.participants.find(p=>p.id===g.anchor_participant)?.name||'Anchor')+' '+g.line:'Line '+g.line):''),'group-title');groupTitle.dataset.group=g.id;section.append(groupTitle);const table=el('table');table.setAttribute('aria-label',e.title+', '+(periods[g.period]||g.period.replaceAll('_',' '))+', '+markets[g.market]+(g.line?', line '+g.line:''));table.dataset.group=g.id;const thead=el('thead'),tr=el('tr');const sh=el('th','Selection');sh.scope='col';tr.append(sh);const shown=Object.keys(venues).filter(v=>!filters.venue||filters.venue===v);for(const v of shown){const th=el('th',venues[v]+(v==='novig'||v==='prophetx'?' · eq':''));th.scope='col';tr.append(th);}for(const name of ['EV %']){const th=el('th',name);th.scope='col';tr.append(th);}thead.append(tr);table.append(thead);const tbody=el('tbody');
for(const o of g.outcomes){rows++;const row=el('tr');row.dataset.outcome=o.id;const th=el('th',o.label,'outcome');th.scope='row';row.append(th);const visibleQuotes=Object.fromEntries(shown.map(v=>[v,o.quotes[v]]));for(const v of shown){const td=el('td');td.dataset.venue=venues[v];td.dataset.venueKey=v;const q=o.quotes[v];if(!q||q.state==='unavailable'||q.state==='error'){td.append(el('div',q?.state==='error'||['unavailable','error','stopped'].includes(payload.source_status?.[v]?.state)?'Source unavailable':payload.source_status?.[v]?.state==='connecting'?'Connecting':payload.source_status?.[v]?.state==='resyncing'?'Refreshing source':'Selection unavailable','unavailable'));}else{const b=el('button',undefined,'price');b.type='button';b.dataset.quote=q.id;fillPrice(b,q,visibleQuotes);if(selectedId===q.id)b.classList.add('selected');b._selection={event:e,group:g,outcome:o,quote:q,comparisonQuotes:visibleQuotes,mode:payload.mode};b._onSelect=onSelect;b.addEventListener('click',()=>{if(b._selection)b._onSelect(b._selection,b);});buttons.set(q.id,{button:b,q,quotes:visibleQuotes,event:e,group:g,outcome:o});td.append(b);for(const alt of o.alternatives?.[v]||[]){const ab=el('button',undefined,'price alternative');ab.type='button';ab.dataset.quote=alt.id;ab._selection={event:e,group:g,outcome:o,quote:alt,comparisonQuotes:visibleQuotes,mode:payload.mode};ab._onSelect=onSelect;fillPrice(ab,alt,visibleQuotes);ab.addEventListener('click',()=>{if(ab._selection)ab._onSelect(ab._selection,ab);});buttons.set(alt.id,{button:ab,q:alt,quotes:visibleQuotes,event:e,group:g,outcome:o});td.append(ab);}}row.append(td);}const metricQuotes=Object.values(o.quotes).filter(q=>q&&(!filters.venue||q.venue===filters.venue));for(const key of ['ev']){const td=el('td');td.dataset.venue=key==='arbitrage'?'Arb %':'EV %';const values=metricQuotes.map(q=>q.calculations?.[key]).filter(Boolean);const supported=values.filter(r=>r.eligible);const r=supported[0]||values[0];td.append(el('strong',r?.eligible?r.display_value:'Unavailable'));td.append(el('div',r?.eligible?(key==='arbitrage'?'Gross · conditional · '+(r.basis?.inputs||[]).map(x=>venues[x.venue]).join(' + '):'Independent model basis'):r?.reason||'Calculation basis unavailable','age'));row.append(td);}tbody.append(row);}table.append(tbody);section.append(table);}root.append(section);}
return {events,rows,buttons};}
export function renderDetails(root,selection,onClose,onLatest,options={}){root.replaceChildren();root.classList.toggle('expired',selection.expired);const {event:e,group:g,outcome:o,quote:q}=selection;const top=el('div',undefined,'detail-top'),heading=el('div',undefined,'detail-heading');heading.append(el('h2','Price details'));const close=el('button','×','close');close.setAttribute('aria-label','Close price details');close.id='close-details';close.addEventListener('click',onClose);heading.append(close);top.append(heading,el('div',o.label,'selection-label'),el('div',e.title,'detail-game'),el('div',(periods[g.period]||g.period.replaceAll('_',' '))+' · '+markets[g.market]+(g.line?' · '+g.line:''),'detail-game'));const priceLine=el('div',q.display.supported?q.display.american:'Conversion unavailable','detail-price');if(q.display.supported)priceLine.append(el('small',' / '+q.display.cents+'c'+(q.display.equivalent?' eq':'')));else priceLine.append(el('small',q.display.reason||'Unsupported quote basis'));top.append(priceLine,el('div',venues[q.venue]+' · '+(options.live?'Live revision ':'Selected revision ')+q.revision+(selection.mode==='synthetic'?' · Synthetic test data':''),'revision'));root.append(top);const notice=el('div',undefined,'notice');notice.id='selection-notice';notice.hidden=true;root.append(notice);
function section(title){const s=el('section',undefined,'detail-section');s.append(el('h3',title));root.append(s);return s;}
function pairs(s, values){const dl=el('dl');for(const [k,v]of values)dl.append(el('dt',k),el('dd',v));s.append(dl);}
const original=section('Original quote & conversion');pairs(original,[['Native value',q.original.value+' '+(q.original.units==='decimal_odds'?'decimal odds':q.original.units==='cents_per_contract'?'cents':'USD / contract')],['Normal-win payout',q.original.payout===null?'Unknown':q.original.payout+' '+(q.original.payout_units||'unknown units')],['Displayed cents',q.display.equivalent?'Equivalent · 100 / decimal odds':q.original.units==='cents_per_contract'?'Native cents · unchanged':'Native USD · price × 100'],['American basis',q.original.units==='decimal_odds'?'Original decimal '+q.original.value:q.original.units==='cents_per_contract'?'d = 100 / '+q.original.value:'d = 1 / '+q.original.value]]);if(q.original.native_value!==undefined)pairs(original,[['Original source value',q.original.native_value+' '+q.original.native_units],['Transformation',q.original.transformation.replaceAll('_',' ')]]);original.append(el('p','Rounded for reading: whole American odds, 0.1 cent. Calculations retain original inputs. Conversion does not establish matching settlement.'));
const times=section('Observation times');function time(v){return v===null?'Unknown':new Date(v).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'})+' ET';}pairs(times,[['Source',time(q.times.source_at)],['Received',time(q.times.received_at)],['Projected',time(q.times.projected_at)],[options.live?'Source age':'Source age at selection',q.age_seconds===null?'Unknown':Math.floor(q.age_seconds)+'s'],['Source state',q.state+(q.stale?' · stale':'')]]);times.append(el('p',options.live?'Prices follow the current odds board. Receipt and browser connection are separate from source freshness.':'Receipt and browser connection are not source freshness. This review is held for up to 5 minutes.'));
if(q.book_confirmation){const c=q.book_confirmation;const confirmed=section('Complete book confirmation');pairs(confirmed,[['Confirmed book timestamp',time(c.confirmed_at)],['Captured confirmation age',q.confirmation_age_seconds===null?'Unknown':Math.floor(q.confirmation_age_seconds)+'s'],['Basis',c.basis],['Generation / sequence',c.generation+' / '+(c.sequence??'Not supplied')]]);confirmed.append(el('p','A validated complete provider book can confirm an unchanged price. This timestamp is separate from the original source clock and price revision.'));const proof=el('details');proof.append(el('summary','Confirmation evidence'));for(const k of ['market_id','request_id','subscription_id','payload_sha256','sha256'])proof.append(el('p',k+': '+(c[k]??'Not supplied')));confirmed.append(proof);}
const rules=section('Settlement & costs');rules.append(el('p',q.rule_note),el('p',q.cost_note||(q.calculation_inputs?'Supplied costs and depth apply only to the bound calculation inputs. Verify current venue terms and quantity.':'Fees and executable depth are unknown. Quotes are gross; verify current terms and quantity at the venue.')));
const calc=section('Calculations');function calculation(name,value,reason){const d=el('div',undefined,'calculation');d.append(el('strong',name),el('span',value));if(reason)d.append(el('p',reason));calc.append(d);}
if(options.production){
for(const [key,name] of [['raw_difference','Raw price difference'],['ev','EV %'],['sizing','Sizing']]){const r=q.calculations[key];calculation(name,r?.eligible?(r.display_value||r.value+' '+(r.unit||'')):'Unavailable',r?.eligible?(key==='raw_difference'?(r.interpretation||'Lowest other eligible venue minus selected price. Gross only.'):r.scope||'Original bound calculation inputs'):r?.reason||'Required inputs unavailable');}
const manual=el('details');manual.append(el('summary','Manual dollar What-if'));manual.id='manual-workspace';calc.append(manual);options.renderManual?.(manual);
}else{options.renderPreviewCalculations?.(calculation,q,selection);}

if(q.native_predicate){const native=section('Native predicate & domain');native.append(el('p','Selected native '+q.native_predicate.predicate+' for '+q.native_predicate.participant+'. Native outcomes: '+q.native_predicate.domain.map(s=>s.native_outcome_id+': '+s.participant+' '+s.predicate).join('; ')+'. Gross comparison only; exceptional cashflows are separate.'));}
const ids=section('Selection identity');pairs(ids,[['Selection binding',q.source.binding_id],['Venue revision',String(q.revision)],['Native side',q.source.native_side]]);const disclosure=el('details');disclosure.append(el('summary','Exact source IDs'));for(const k of ['native_event_id','native_market_id','native_outcome_id'])disclosure.append(el('p',k+': '+q.source[k]));ids.append(disclosure);return close;
}

// Keyed reconciliation for structural catalog changes and price updates.
function nodeKey(n){if(n.nodeType!==1)return null;return [n.tagName,n.dataset.quote||n.dataset.outcome||n.dataset.event||n.dataset.group||n.dataset.venueKey||''].join(':');}
function syncNode(old,next){
 if(old.nodeType===3){if(old.data!==next.data)old.data=next.data;return;}
 for(const a of [...old.attributes])if(!next.hasAttribute(a.name))old.removeAttribute(a.name);
 for(const a of [...next.attributes])if(old.getAttribute(a.name)!==a.value)old.setAttribute(a.name,a.value);
 if(next._selection){old._selection=next._selection;old._onSelect=next._onSelect;}
 const previous=[...old.childNodes];const used=new Set();let position=old.firstChild;
 for(const desired of [...next.childNodes]){
   const key=nodeKey(desired);let found=previous.find(n=>!used.has(n)&&n.nodeType===desired.nodeType&&(key?nodeKey(n)===key:n.nodeType===3));
   if(found){used.add(found);syncNode(found,desired);if(found!==position)old.insertBefore(found,position);position=found.nextSibling;}
   else{old.insertBefore(desired,position);position=desired.nextSibling;}
 }
 for(const stale of previous)if(!used.has(stale)&&stale.parentNode===old){
   if(stale.nodeType===1&&stale.contains(document.activeElement)){stale.dataset.removed='true';for(const b of stale.matches('button')?[stale]:stale.querySelectorAll('button')){b._selection=null;b.setAttribute('aria-disabled','true');b.replaceChildren(el('span','Price removed · inspection only','unavailable'));}}
   else stale.remove();
 }
}
export function reconcileBoard(root,payload,filters,onSelect,selectedId){
 const focused=document.activeElement;
 const positions=[...root.querySelectorAll('[data-outcome]')].map(node=>({node,id:node.dataset.outcome,rect:node.getBoundingClientRect()}));
 const temp=el('section');for(const a of [...root.attributes])temp.setAttribute(a.name,a.value);const result=renderBoard(temp,payload,filters,onSelect,selectedId);
 const surviving=new Set(result.events.flatMap(e=>e.groups.flatMap(g=>g.outcomes.map(o=>o.id))));
 const focusedRow=focused?.closest('[data-outcome]');
 const visible=p=>p.rect.bottom>0&&p.rect.top<innerHeight;
 // Prefer a visible focused row; otherwise choose the first SURVIVING reading
 // row. A removed first-visible row must not erase an available next anchor.
 const anchor=positions.find(p=>p.node===focusedRow&&visible(p))||positions.find(p=>visible(p)&&surviving.has(p.id))||positions.find(p=>surviving.has(p.id));
 syncNode(root,temp);
 if(focused?.isConnected&&document.activeElement!==focused)focused.focus({preventScroll:true});
 if(anchor){const current=[...root.querySelectorAll('[data-outcome]')].find(n=>n.dataset.outcome===anchor.id);if(current)window.scrollBy(0,current.getBoundingClientRect().top-anchor.rect.top);}
 for(const [id,ref] of result.buttons){ref.button=[...root.querySelectorAll('[data-quote]')].find(n=>n.dataset.quote===id);}
 return result;
}
