'use strict';
const $=id=>document.getElementById(id);
const esc=x=>String(x??'Unavailable').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sessions=[],sequence=0,last=null;const params=new URLSearchParams(location.search);let referenceId=params.get('reference')||null;let view=params.get('view')||'arb',candidate=params.get('candidate')||'cross-buffalo';
const money=x=>x==='Unavailable'?x:(x.startsWith('-')?'−$'+x.slice(1):'$'+x);const pct=x=>x==='Unavailable'?x:x+'%';
const metric=(label,value,cls='')=>`<div><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong></div>`;
const sign=x=>x==null||/^[-+]?0*(?:\.0*)?$/.test(String(x))?'':String(x).startsWith('-')?'negative':'positive';
function session(){return E5State.select(sessions,$('session').value);}
function cuts(key){const s=session();if(key&&s.game?.product_identity&&!s.timeline.some(t=>t.id===key))s.timeline.push({id:key,at:'Retained observation',label:'Verified immutable cutoff'});$('cutoff').innerHTML=s.timeline.map((t,i)=>`<option value="${esc(t.id)}">${i+1} / ${s.timeline.length} · ${esc(t.at)} · ${esc(t.label)}</option>`).join('');$('cutoff').value=key||s.timeline[s.default_cutoff].id;}
function bookmark(){const q=new URLSearchParams({session:$('session').value,hash:session().hash,cutoff:$('cutoff').value,quantity:$('quantity').value,scenario:$('scenario').value,probability:$('probability').value,basis:$('basis').value,contract:$('contract').value||'polymarket_us:1315440',view,candidate});if(referenceId)q.set('reference',referenceId);if(params.get('research')==='true')q.set('research','true');const current=new URLSearchParams(location.search);if(current.get('session')===q.get('session')&&current.get('cutoff')===q.get('cutoff'))for(const k of ['resolution_session','resolution_cutoff','resolution_asof'])if(current.has(k))q.set(k,current.get(k));history.replaceState(null,'','?'+q);return q;}
function showView(){ $('arb').hidden=view!=='arb';$('ev').hidden=view!=='ev';$('arb-tab').setAttribute('aria-pressed',view==='arb');$('ev-tab').setAttribute('aria-pressed',view==='ev');}
function legHTML(l){return `<div class="leg"><small>${esc(l.label)}</small><strong>${esc(l.contract)}</strong><p>Buy ${esc(money(l.display.ask))}</p></div>`;}
function candidateHTML(c){const d=c.display;return `<article class="candidate ${candidate===c.id?'selected':''}" data-candidate="${c.id}"><div class="candidate-heading"><h3>${c.legs.length>2?'Cross-venue portfolio':'Cross-venue pair'}</h3><span class="badge">${esc(BoardView.status(c,c.profit))}</span></div><div class="legs">${c.legs.map(legHTML).join('')}</div><div class="metrics primary">${metric('Net $',money(d.profit),sign(c.profit))}${metric('Size per leg',c.modeled_quantity+(c.depth_limited?' · depth limited':''))}</div>${BoardView.reasons(c).length?`<p class="warning">${esc(BoardView.reasons(c).join(' · '))}</p>`:''}<button data-explore="${c.legs[0].id}">What-if EV →</button><details><summary>Details</summary><div class="metrics">${metric('ROI',pct(d.return_pct))}${metric('Entry cash',money(d.cash))}${metric('Fees',money(d.fees))}${metric('Purchase cost',money(d.notional))}</div><p>${esc(last.assumptions)}</p>${c.score_partitions?'<p>Score partitions: '+esc(JSON.stringify(c.score_partitions))+'. Equality follows each native predicate; pushes return purchase stake, with entry fees retained.</p>':''}<p>Net = normal payout − purchase cost − fees. ROI uses entry cash. Top prices are not average fills. Alternatives share liquidity. All-outcome worst case is unavailable.</p><pre>${esc(JSON.stringify({reasons:c.reasons,normal_cashflows:c.normal_cashflows,settlement:c.settlement,legs:c.legs.map(l=>({contract:l.contract,top_size:l.top_size,visible_size:l.visible_size,book_id:l.book_id,received_at:l.received_at,source_at:l.source_at,transformation:l.transformation,fills:l.fills,fee_audit:l.fee_audit}))},null,2))}</pre></details></article>`;}
function researchHTML(e){if(!e)return '';const d=e.display;return `<h2>Page-derived research estimate</h2><p class="warning">${esc(e.label)}</p><p>${esc(e.bookmaker==='draftkings'?'DraftKings':e.bookmaker)} via VegasInsider · full-game moneyline</p><div class="legs">${e.sides.map(s=>`<div class="leg"><strong>${esc(s.team)} · ${esc(s.percent)}%</strong><small>Original odds ${esc(s.odds)}</small></div>`).join('')}</div><p class="muted">Source retrieved ${esc(e.reference_retrieved_at)}<br>Target observed ${esc(e.target_received_at)}<br>Bookmaker update time and delay unknown.</p><div class="metrics primary">${metric(e.target_team+' YES conditional EV',money(d.expected_profit),sign(e.expected_profit))}${metric('Requested / available contracts',e.quantity+' / '+(e.leg.visible_size??'unknown'))}${metric('ROI on entry cash',pct(d.return_pct))}</div><p>Ordinary completed-game winners, including overtime. Unconditional EV unavailable: exceptional probability mass and payouts unknown. No verified current fair value or executable edge.</p><p class="muted">Historical fee scenario: ${esc(e.fee_scenario==='unknown'?'unresolved fees':e.fee_scenario==='cent'?'cent balance':'0.0001 balance')} · account applicability unverified. Uses the original target above at every cutoff.</p>${e.reasons.length?`<p class="warning">${esc(e.reasons.join(' · '))}</p>`:''}<details><summary>Details · calculation, evidence and exceptions</summary><div class="metrics">${metric('Expected payout',money(d.expected_payout))}${metric('Purchase cost',money(d.notional))}${metric('Fees',money(d.fee))}${metric('Entry cash',money(d.cash))}</div><p>${esc(e.fee_basis)}</p><p>Expected payout = target-team probability × size. Conditional net = expected payout − entry cash; ROI = conditional net / entry cash. Assessment ${esc(e.assessment.assessed_at)}. Ordinary-winner comparability does not establish full settlement equivalence.</p><p>${esc(e.assessment.conclusion)}</p><ul>${e.assessment.exceptional_differences.map(x=>`<li><b>${esc(x.outcome)}</b> · DraftKings: ${esc(x.draftkings)} Kalshi: ${esc(x.kalshi)}</li>`).join('')}</ul><ul>${e.assessment.evidence.map(x=>`<li>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noreferrer">${esc(x.section)}</a>`:esc(x.file)} · ${esc(x.summary||x.quote)} ${esc(x.basis||'')}</li>`).join('')}</ul><pre>${esc(JSON.stringify({binding:e.assessment.binding,observation_times:e.assessment.observation_times,probability:e.probability,expected_payout:e.expected_payout,expected_profit:e.expected_profit,return_pct:e.return_pct,fee_scenario:e.fee_scenario,fills:e.leg.fills,fee_audit:e.leg.fee_audit,limitations:e.limitations},null,2))}</pre></details>`;}
function render(r){last=r;$('scenario').disabled=!!r.fee_scenario_locked;if(r.fee_scenario_locked)$('scenario').value='unknown';$('page-research').hidden=!r.page_estimate;$('page-research').innerHTML=researchHTML(r.page_estimate);if(r.game){$('game-title').textContent=r.game.title;$('data-mode').textContent=(r.data_mode||session().data_mode)+' · frozen retained cutoff';$('contract').innerHTML=r.contracts.map(c=>`<option value="${esc(c.id)}">${esc(c.contract+' · '+c.label)}</option>`).join('');$('contract').value=r.ev.leg.id;} $('assumptions').textContent=r.assumptions;$('cutoff-label').textContent='Captured cutoff · '+r.cutoff;const s=session();const i=s.timeline.findIndex(t=>t.id===$('cutoff').value);$('previous').disabled=i<=0;$('next').disabled=i>=s.timeline.length-1;
$('freshness').innerHTML=[...new Set(r.contracts.map(c=>c.venue))].map(v=>{const c=r.contracts.find(x=>x.venue===v);return `<div><b>${esc(c.label)}</b> · ${esc(c.connection)}<br>Receipt age ${esc(c.age_seconds)} seconds at cutoff<br>${esc(c.warnings.filter(x=>x!=='No supported purchasable ask').join(' · ')||'Receipt fresh at cutoff')}</div>`}).join('');
$('outcome-note').textContent=r.fee_scenario_locked?'Native fee applicability and settlement charges unresolved; net values unavailable.':r.score_partitions?(r.game?.product_identity?.family==='futures'?'Championship outcomes only; every declared state is evaluated. Unknown exceptional payouts remain unavailable.':r.game?.product_identity?.period==='first_half'?'Conditional net across every reachable first-half score partition, including ties. Second-half and overtime scoring excluded. Exceptional payouts unresolved.':'Conditional net across every reachable completed-game score partition. Exceptional settlement and account fees unresolved.'):'Conditional net · normal winners and modeled fees. Exceptional settlement and account fees unresolved.';
$('probability-scope').textContent=r.score_partitions?(r.game?.product_identity?.family==='futures'?'Championship outcomes only; every declared state is evaluated. Unknown exceptional payouts remain unavailable.':r.game?.product_identity?.period==='first_half'?'Completed first-half score only; no second half or overtime. Winner ties and integer-line equality require an imported partition distribution with explicit probability mass. Half-point lines accept a labeled outcome probability. Pushes use reviewed refund terms; exceptional outcomes remain unknown.':'Completed-game score only. Half-point lines accept a labeled outcome probability; integer lines require an imported partition distribution including equality mass. Pushes use the reviewed refund terms. Exceptional outcomes remain unknown.'):'Normal winners only; excludes tie, void, refund and discretionary outcomes.';
$('candidates').innerHTML=r.candidates.filter(BoardView.crossVenue).map(candidateHTML).join('');const e=r.ev,d=e.display,l=e.leg;
$('probability-origin').textContent=referenceId?'Dated reference probability · '+e.probability_source+'. Editing the probability or basis creates a separate manual assumption.':'Owner-entered assumption: enter a probability and basis for this outcome. This tool does not use the page-derived estimate.';
$('ev-result').innerHTML=`<article class="candidate"><div class="candidate-heading"><h3>${esc(l.contract)} · ${esc(l.label)}</h3><span class="badge">${esc(BoardView.status(e,e.expected_profit))}</span></div><p>Buy ${esc(money(l.display.ask))} · p = ${esc(typeof e.probability==='object'&&e.probability!==null?JSON.stringify(e.probability):e.probability??'not entered')}</p><div class="metrics primary">${metric(referenceId?'Reference conditional net $':'What-if net $',money(d.expected_profit),sign(e.expected_profit))}${metric('Size',e.modeled_quantity+(e.depth_limited?' · depth limited':''))}</div><p class="warning">${esc(BoardView.reasons(e).join(' · '))}</p><details><summary>Details</summary><div class="metrics">${metric('ROI',pct(d.return_pct))}${metric('Break-even',pct(d.break_even_pct))}${metric('Expected payout',money(d.expected_payout))}${metric('Entry cash',money(l.display.cash))}</div><p>${esc(e.reference_limitation||'')} ${esc(e.conditional_on)}. ${esc(e.probability_source)}.</p><p>${esc(r.assumptions)}</p><p>${e.score_partitions?'Expected profit = sum of each partition probability × its net cashflow. Integer lines require explicit equality mass.':'Expected profit = p × win net cashflow + (1 − p) × loss net cashflow.'}</p><pre>${esc(JSON.stringify({cashflows:l.cashflows,fill_assumptions:l.fills,fee_audit:l.fee_audit},null,2))}</pre></details></article>`;
$('provenance').innerHTML=(r.references?.length?'<h2>Dated references</h2>'+r.references.map(ref=>'<p><b>'+esc(ref.role==='model_reference'?'Model reference':'Delayed Pinnacle reference')+'</b> · '+esc(ref.provider_id)+' / '+esc(ref.origin_id)+' · '+esc(ref.value_kind)+' '+esc(typeof ref.value==='object'?JSON.stringify(ref.value):ref.value)+'<br>As of '+esc(ref.source_at||ref.model_as_of||'unknown')+' · received '+esc(ref.received_at)+'<br>'+esc(ref.delay_basis||'Delay unknown')+' · '+esc(ref.freshness||'dated')+'<br>'+esc(ref.dependency||'Independence unknown')+'<br>'+esc(ref.reason||'Conditional normal-winner estimate; exceptional outcomes unknown')+'</p>').join('')+'<details><summary>Original reference inputs</summary><pre>'+esc(JSON.stringify(r.references,null,2))+'</pre></details>':'')+`<p>Assessment ${esc(r.assessment.assessed_at)} · historical observations ${esc(r.cutoff)}. ${esc(r.assessment.note)}</p><p>${esc(r.coverage.limitation)} ${esc(r.coverage.completeness)}</p><p>Retained US coefficient: ${esc(r.assessment.pmus_coefficient)}. <a href="https://docs.polymarket.us/fees" target="_blank" rel="noreferrer">US fee documentation</a> announces a change after these captures; historical scenarios retain 0.06. <a href="https://docs.kalshi.com/getting_started/fee_rounding" target="_blank" rel="noreferrer">Kalshi rounding documentation</a>.</p><pre>${esc(JSON.stringify({session:r.session,hash:r.hash,sources:r.assessment.sources},null,2))}</pre>`;showView();}
async function calculate(){const n=++sequence;$('error').textContent='Calculating…';$('arb').setAttribute('aria-busy','true');$('ev').setAttribute('aria-busy','true');try{const q=bookmark();const response=await fetch('/api/calculate?'+q);const r=await response.json();if(n!==sequence)return;if(!response.ok)throw Error(r.error);render(r);$('error').textContent='';window.PredictResolution?.load(q);}catch(e){if(n!==sequence)return;$('error').textContent=e.message;$('candidates').replaceChildren();$('ev-result').replaceChildren();$('page-research').replaceChildren();$('page-research').hidden=true;}finally{if(n===sequence){$('arb').removeAttribute('aria-busy');$('ev').removeAttribute('aria-busy');}}}
async function init(){try{sessions=await (await fetch('/api/sessions?'+params)).json();$('session').innerHTML=sessions.map(s=>`<option value="${s.id}">${esc(s.label)}</option>`).join('');if(params.has('session')){if(!E5State.select(sessions,params.get('session')))throw Error('Unknown saved session');$('session').value=params.get('session');if(params.get('hash')!==session().hash)throw Error('Saved session identity changed');}cuts(params.get('cutoff'));if(!$('cutoff').value)throw Error('Unknown saved cutoff');$('contract').innerHTML=Object.entries(session().game?.sides||{}).map(([k,s])=>`<option value="${esc(k)}">${esc(s.participant+' · '+k)}</option>`).join('');for(const id of ['quantity','scenario','probability','contract','basis'])if(params.has(id))$(id).value=params.get(id);if(!referenceId&&!params.has('probability'))loadAssumption();showView();await calculate();if(params.get('research')==='true')$('page-research').scrollIntoView({block:'start'});}catch(e){$('error').textContent=e.message;}}
$('session').onchange=()=>{referenceId=null;cuts();$('contract').innerHTML=Object.entries(session().game.sides).map(([k,s])=>`<option value="${esc(k)}">${esc(s.participant+' · '+k)}</option>`).join('');$('probability').value='';$('basis').value='';calculate()};$('cutoff').onchange=calculate;for(const id of ['quantity','scenario'])$(id).onchange=calculate;for(const id of ['probability','basis'])$(id).onchange=()=>{referenceId=null;saveAssumption();calculate()};$('contract').onchange=()=>{referenceId=null;loadAssumption();calculate()};$('calculate').onclick=()=>{saveAssumption();calculate()};
for(const [id,delta] of [['previous',-1],['next',1]])$(id).onclick=()=>{const s=session(),i=s.timeline.findIndex(t=>t.id===$('cutoff').value);$('cutoff').value=s.timeline[i+delta].id;calculate()};
for(const v of ['arb','ev'])$(v+'-tab').onclick=()=>{view=v;showView();bookmark()};
$('candidates').onclick=e=>{const select=e.target.dataset.select,explore=e.target.dataset.explore;if(select){candidate=select;bookmark();render(last)}if(explore){candidate=e.target.closest('[data-candidate]').dataset.candidate;$('contract').value=explore;loadAssumption();view='ev';showView();calculate()}};
function loadAssumption(){const g=session()?.game;if(!g)return;const a=JSON.parse(localStorage.getItem('predict-ev-assumptions')||'{}')[g.id+'~'+$('contract').value];$('probability').value=a?.probability||'';$('basis').value=a?.basis||'';}
function saveAssumption(){
 if(referenceId)return;
 const g=session()?.game;if(!g)return;const key=g.id+'~'+$('contract').value;
 const all=JSON.parse(localStorage.getItem('predict-ev-assumptions')||'{}');
 if($('probability').value!==''&&$('probability').validity.valid&&$('basis').value.trim())all[key]={probability:$('probability').value,basis:$('basis').value.trim()};
 else if($('probability').value==='')delete all[key];
 localStorage.setItem('predict-ev-assumptions',JSON.stringify(all));
}
$('back').onclick=e=>{e.preventDefault();if($('probability').value!==''&&$('basis').value.trim())saveAssumption();location.href='/'+(sessionStorage.getItem('predict-dashboard-query')||'');};
init();
