'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let query=new URLSearchParams(location.search),view=query.get('view')||'arb',busy=false,pendingRefresh=false,last=null,pollTimer=null,followSession=null;
const fields=['quantity','scenario','sort','venue','freshness','search','positive','period','family','competition','season'];
for(const key of fields)if(query.has(key)){if(key==='positive')$(key).checked=query.get(key)==='true';else $(key).value=query.get(key);}
function inputs(){const q=new URLSearchParams({view});for(const key of fields)q.set(key,key==='positive'?String($(key).checked):$(key).value);if($('capture').value)q.set('capture',$('capture').value);return q;}
function fmt(n,suffix=''){return n===null||n===undefined?'Unavailable':Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})+suffix;}
function link(r){const q=new URLSearchParams({session:r.session,hash:r.hash,cutoff:r.cutoff,quantity:$('quantity').value,scenario:$('scenario').value,candidate:r.candidate,view:view==='ev'?'ev':'arb'});q.set('contract',r.contract||r.legs[0].id);if(r.reference_id)q.set('reference',r.reference_id);if(view==='research')q.set('research','true');if(view==='ev'&&r.probability!=null&&typeof r.probability!=='object'){q.set('probability',r.probability);q.set('basis',r.assumption);}return '/game?'+q;}
function rememberDetails(root){return new Set([...root.querySelectorAll('details[data-detail-key][open]')].map(d=>d.dataset.detailKey));}
function restoreDetails(root,keys){for(const d of root.querySelectorAll('details[data-detail-key]'))d.open=keys.has(d.dataset.detailKey);}
// Snapshot focus immediately before replacing markup, not before the request.
// Match retained identities rather than row position; never select a different row.
function rememberFocus(){
 const element=document.activeElement;
 const owner=element?.closest('#rows tr[data-id], #product-coverage details[data-detail-key]');
 if(!owner)return null;
 const key=element.dataset.focusKey||(element.tagName==='SUMMARY'?'summary':null);
 const href=element.tagName==='A'?element.getAttribute('href'):null;
 if(!key&&!href)return null;
 return {root:owner.dataset.id!==undefined?'rows':'product-coverage',id:owner.dataset.id??owner.dataset.detailKey,key,href};
}
function restoreFocus(focus){
 if(!focus||document.activeElement!==document.body)return;
 const selector=focus.root==='rows'?'tr[data-id]':'details[data-detail-key]';
 const owner=[...$(focus.root).querySelectorAll(selector)].find(e=>(e.dataset.id??e.dataset.detailKey)===focus.id);
 if(!owner)return;
 const target=[...owner.querySelectorAll('summary, a[href]')].find(e=>focus.key?(e.dataset.focusKey||(e.tagName==='SUMMARY'?'summary':null))===focus.key:e.getAttribute('href')===focus.href);
 if(target&&target.getClientRects().length)target.focus({preventScroll:true});
}
function render(r,stable=false){
 const focus=last?.capture===r.capture?rememberFocus():null;
 const openRows=new Set([...document.querySelectorAll('#rows tr')].filter(x=>x.querySelector('details[open]')).map(x=>x.dataset.id));
 renderContent(r,stable);
 for(const row of document.querySelectorAll('#rows tr'))if(openRows.has(row.dataset.id)){const detail=row.querySelector('details');if(detail)detail.open=true;}
 restoreFocus(focus);
}
function renderContent(r,stable=false){const openCoverage=rememberDetails($('product-coverage'));r.rows=r.rows.filter(x=>view!=='arb'||BoardView.crossVenue(x));if(stable&&last?.capture===r.capture){const order=new Map(last.rows.map((x,i)=>[x.id,i]));r.rows.sort((a,b)=>(order.get(a.id)??1e9)-(order.get(b.id)??1e9));}last=r;$('scenario').disabled=!!r.fee_scenario_locked;if(r.fee_scenario_locked)$('scenario').value='unknown';const s=r.status;if(s.active&&!pollTimer)pollTimer=setTimeout(poll,1500);$('max-games').disabled=s.active;$('max-games').parentElement.hidden=['d2-bounded-inventory','product-session'].includes(s.operating_mode);$('start').textContent=s.operating_mode==='d2-bounded-inventory'?'Start coverage scan':'Start scan';if(s.fixed_duration)$('duration').value=s.fixed_duration;$('duration').disabled=s.active||!!s.fixed_duration;$('start').disabled=!s.start_available;$('stop').disabled=!s.active;$('mode').textContent=!r.capture?'No scan selected':BoardView.mode(r.data_mode,r.live,r.state);$('scan-state').textContent=BoardView.scanStatus(s);if(s.fixed_duration)$('scan-state').textContent+=' Duration is fixed at '+s.fixed_duration+' seconds.';if(s.error)$('scan-state').textContent+=' · '+s.error;
 r.sources=r.sources||[...new Set(r.rows.flatMap(x=>x.venues||[]))].map(v=>({source_id:v,label:v,role:'prediction'}));const sourceChoice=$('venue').value;if(r.sources.length){$('venue').innerHTML='<option value="">All sources</option>'+r.sources.filter(x=>x.role==='prediction').map(x=>`<option value="${esc(x.source_id)}">${esc(x.label)}</option>`).join('');$('venue').value=sourceChoice;}
 const chosen=r.capture;$('capture').innerHTML=r.captures.map(c=>`<option value="${esc(c.id)}">${esc(BoardView.captureLabel(c.label))}</option>`).join('');$('capture').value=chosen||'';
 const c=r.coverage;$('coverage').textContent=c?`${c.selected} games · ${c.excluded.length} excluded · ${c.truncated_by_limit} beyond limit`:'Discovery pending';$('coverage-detail').textContent=JSON.stringify(c,null,2);$('product-coverage').innerHTML=r.market_catalog?'<p class="source-summary">'+r.sources.map(x=>'<span>'+esc(x.label)+': '+esc(BoardView.sourceState(x.coverage?.state||x.state))+(x.coverage?.reason?' — '+esc(x.coverage.reason):'')+'</span>').join('')+'</p><details data-detail-key="markets"><summary>Market coverage and source details</summary><p>'+r.sources.map(x=>esc(x.label)+(x.selected?' · selected':'')+' · '+esc(x.environment||'environment unknown')+' · '+esc(x.update_path||'update method unknown')).join('<br>')+'</p>'+r.market_catalog.map(m=>'<p>'+esc(m.title)+' · '+esc(m.source_id)+' · '+esc(m.identity?.family)+' / '+esc(m.identity?.period)+' / '+esc(m.identity?.line??'no line')+' · '+esc(m.reason||(m.usable?(r.state==='saved'?'retained at cutoff':'receiving'):'awaiting usable book'))+(m.received_at?' · '+esc(m.update_path)+' · received '+esc(m.received_at):'')+(m.native?.display_prices||[]).map(p=>' · '+esc(p.label)+': displayed '+esc(p.available??'unavailable')+' / last trade '+esc(p.last??'unknown')+' (size unknown)').join('')+(m.quotes||[]).map(q=>' · '+esc(q.side)+': '+(q.ask==null?'ask unavailable':'$'+esc(q.ask))+' / '+(q.ask_size==null?'size unknown':esc(q.ask_size)+' '+esc(q.unit))).join('')+'</p>').join('')+'</details>':'';if(r.references?.length)$('product-coverage').innerHTML+='<details data-detail-key="references"><summary>Saved references · '+r.references.length+'</summary>'+r.references.map(ref=>'<div class="retained-reference">'+esc(ref.provider_id)+' / '+esc(ref.origin_id)+' · '+esc(ref.market_identity?.competition)+' · '+esc(ref.participant)+' · '+esc(ref.value_kind)+' '+esc(ref.value)+'<br>'+esc(ref.market_identity?.family)+' / '+esc(ref.market_identity?.period)+' · '+esc(ref.reason||'Dated input; EV requires an exactly matching supported market')+'<br>As of '+esc(ref.source_at||'unknown')+' · received '+esc(ref.received_at)+'<br>'+esc(ref.dependency)+'<br>Scheduled '+esc(ref.market_identity?.scheduled_start)+' · delay '+esc(ref.delay_seconds??'unknown')+'<br>'+esc(ref.delay_basis)+'<details data-detail-key="reference-'+esc(ref.id)+'"><summary>Original input and calculation basis</summary><p>'+esc(ref.conversion_method||'No probability conversion')+'</p><pre>'+esc(JSON.stringify(ref.original_value,null,2))+'</pre><p>Event '+esc(ref.source_event_id)+' · '+esc(ref.evidence_mode)+'<br>'+esc(ref.provenance)+'<br>Cutoff '+esc(r.durable_cursor)+'</p></details></div>').join('')+'</details>';restoreDetails($('product-coverage'),openCoverage);$('updated').textContent=r.capture_time?'Captured '+new Date(r.capture_time).toLocaleString(undefined,{timeZoneName:'short'}):'';$('last-observation').textContent='Last observation: '+(r.last_update||'—');
 $('arb').setAttribute('aria-pressed',view==='arb');$('ev').setAttribute('aria-pressed',view==='ev');$('research').setAttribute('aria-pressed',view==='research');for(const id of ['positive','venue','freshness'])$(id).disabled=view==='research';$('empty').textContent=['competition','season','period','family','search','venue','freshness'].some(k=>$(k).value)||$('positive').checked?'No matches. Change the search or filters, or turn off Positive results only.':!r.capture?'No results yet. Choose a saved scan or use Start scan when available.':r.live&&!r.rows.length&&!r.market_catalog?.some(m=>m.usable)?'Looking for comparable prices. Results will appear here; Stop saves what has been collected.':r.references?.length&&!r.market_catalog?.length?'References saved. EV unavailable: no compatible prediction observations in this session.':'No comparable results in this scan. Check market coverage or choose another saved scan.';$('explanation').textContent=r.fee_scenario_locked?'Net profit is unavailable because fee applicability and settlement charges are unresolved.':view==='research'?'Retrospective, time-mismatched research · saved DraftKings probabilities and Kalshi YES asks. Conditional ordinary winners only; unconditional EV unavailable.':view==='arb'?(r.rows.some(x=>x.score_partitions)?(r.rows.some(x=>x.market_identity?.period==='first_half')?'Conditional net: reviewed scoring periods, including first-half tie / equality states. Later scoring excluded from first-half markets. Exceptional payouts unresolved.':'Net profit covers the reviewed scoring outcomes with modeled fees. Exceptional settlement and account fees remain unknown.'):'Net profit assumes normal winners and modeled fees. Exceptional settlement and account fees remain unknown.'):'Estimate profit with a dated reference, or open a game to enter your probability and basis.';
 if(view==='research'){renderResearch(r);return;}
 $('head').innerHTML='<tr><th>Game</th><th>Net profit ($)</th><th>Contracts per leg</th><th>Buy / top price</th><th>Details</th></tr>';
 $('count').textContent=`${r.rows.length} ${view==='arb'?'cross-venue pairs':'what-if legs'} shown`;$('empty').hidden=r.rows.length>0;
 const selected=sessionStorage.getItem('predict-selected-row');$('rows').innerHTML=r.rows.map(x=>`<tr class="${x.usable?'':'unusable'} ${selected===x.id?'selected':''}" data-id="${esc(x.id)}"><td data-label="Game"><a data-focus-key="game" href="${esc(link(x))}">${esc(BoardView.title(x.game_title).name)}</a>${BoardView.title(x.game_title).context?'<small>'+esc(BoardView.title(x.game_title).context)+'</small>':''}${view==='ev'?'<small>'+esc(x.assumption)+'</small>':''}</td><td data-label="Net profit ($)" class="number ${x.profit?.startsWith('-')?'negative':Number(x.profit)>0?'positive':''}">${esc(fmt(x.profit))}${x.profit!=null||x.status==='Assumption needed'?`<small>${esc(BoardView.status(x,x.profit))}</small>`:''}${BoardView.reasons(x).length?`<small class="warning">${esc(BoardView.reasons(x).join(' · '))}</small>`:''}</td><td data-label="Contracts per leg">${esc(x.modeled_quantity)}<small>${x.depth_limited?'Limited by available size':''}</small></td><td data-label="Buy / top price">${x.legs.map(l=>`<div>${esc(BoardView.words(l.contract))}<small>${esc(l.label)} · ${l.ask==null?'Ask unavailable':'$'+esc(l.ask)}</small></div>`).join('')}</td><td data-label=""><details><summary>Calculation details</summary><p>ROI ${esc(fmt(x.return_pct,'%'))}${view==='ev'?` · Break-even ${esc(fmt(x.break_even_pct,'%'))}`:''}</p><p>${esc(x.assumption)}${x.probability!=null?` · p=${esc(typeof x.probability==='object'?JSON.stringify(x.probability):x.probability)}`:''}</p><p>Scheduled ${esc(new Date(x.start).toLocaleString())}<br>Cutoff ${esc(x.at)}<br>${x.usable?'Usable at cutoff':'Unavailable at cutoff'}</p>${(x.references||[]).map(r=>`<p>${esc(r.role)} · ${esc(r.provider_id)} / ${esc(r.origin_id)} · ${esc(r.value_kind)} ${esc(typeof r.value==='object'?JSON.stringify(r.value):r.value)}<br>As of ${esc(r.model_as_of||r.source_at)} · Received ${esc(r.received_at)} · Delay ${esc(r.delay_seconds??'unknown')}<br>${esc(r.dependency||'Independence unknown')} · ${esc(r.freshness||'dated')}<br>${esc(r.reason||r.delay_basis||'')}<br>${esc(r.provenance)}</p>`).join('')}<a data-focus-key="game-details" href="${esc(link(x))}">Game details →</a></details></td></tr>`).join('');
}

function researchDetails(e){if(!e)return '';return `<p>Source retrieved ${esc(e.reference_retrieved_at)}<br>Target received ${esc(e.target_received_at)}<br>Original target cutoff ${esc(e.target_cutoff)}</p><p>DraftKings via <a href="${esc(e.source_url)}" target="_blank" rel="noreferrer">VegasInsider</a> · bookmaker update time and delay unknown.</p><p>${e.sides.map(s=>esc(s.team)+' '+esc(s.odds)).join(' / ')}</p><p>${esc(e.fee_basis)}</p><p>${esc(e.assessment.conclusion)}</p><p>${e.assessment.exceptional_differences.map(x=>esc(x.outcome)+': '+esc(x.draftkings)+' '+esc(x.kalshi)).join('<br>')}</p><pre>${esc(JSON.stringify({probability:e.probability,arithmetic:e.arithmetic,expected_payout:e.expected_payout,expected_profit:e.expected_profit,return_pct:e.return_pct,entry_cash:e.leg.cash,fee:e.leg.fee,binding:e.assessment.binding,limitations:e.limitations},null,2))}</pre>`;}
function renderResearch(r){
 $('head').innerHTML='<tr><th>Game / purchase</th><th>Page probability</th><th>Ask / size</th><th>Conditional net / ROI</th><th>Assumptions</th></tr>';
 $('count').textContent=`${r.rows.filter(x=>x.probability!=null).length} page-covered games · ${r.rows.length} shown`; $('empty').hidden=r.rows.length>0;
 const selected=sessionStorage.getItem('predict-selected-row');
 $('rows').innerHTML=r.rows.map(x=>`<tr class="${selected===x.id?'selected':''}" data-id="${esc(x.id)}"><td data-label="Game / purchase"><a data-focus-key="game" href="${esc(link(x))}">${esc(BoardView.title(x.game_title).name)}</a>${BoardView.title(x.game_title).context?'<small>'+esc(BoardView.title(x.game_title).context)+'</small>':''}<small>Buy ${esc(x.target_team)} YES · Kalshi</small></td><td data-label="Page probability">${esc(x.research?x.research.sides.find(s=>s.team===x.target_team).percent+'%':x.probability??'Unavailable')}</td><td data-label="Ask / size">${x.legs[0]?.ask==null?'Unavailable':'$'+esc(x.legs[0].ask)}<small>${esc(x.requested_quantity)} requested / ${esc(x.available_size??'unknown')} available</small></td><td data-label="Conditional net / ROI" class="number ${x.profit?.startsWith('-')?'negative':x.profit==null||/^0(?:\.0+)?$/.test(x.profit)?'':'positive'}">${esc(x.profit==null?'Unavailable':'$'+x.research.display.expected_profit)}<small>${esc(x.return_pct==null?'ROI unavailable':x.research.display.return_pct+'% ROI')}</small></td><td data-label="Assumptions">${esc(x.assumption)}<details><summary>Details</summary>${researchDetails(x.research)}${x.source?`<pre>${esc(JSON.stringify(x.source,null,2))}</pre>`:''}${(x.references||[]).map(r=>`<p>${esc(r.role)} · ${esc(r.provider_id)} / ${esc(r.origin_id)} · ${esc(r.value_kind)} ${esc(typeof r.value==='object'?JSON.stringify(r.value):r.value)}<br>As of ${esc(r.model_as_of||r.source_at)} · Received ${esc(r.received_at)} · Delay ${esc(r.delay_seconds??'unknown')}<br>${esc(r.dependency||'Independence unknown')} · ${esc(r.freshness||'dated')}<br>${esc(r.reason||r.delay_basis||'')}<br>${esc(r.provenance)}</p>`).join('')}<a data-focus-key="game-details" href="${esc(link(x))}">Game details →</a></details></td></tr>`).join('');
}

async function refresh(stable=false){if(busy){if(stable!==true)pendingRefresh=true;return;}busy=true;try{const q=inputs();if(!q.has('capture')&&query.has('capture'))q.set('capture',query.get('capture'));q.set('assumptions',localStorage.getItem('predict-ev-assumptions')||'{}');const response=await fetch('/api/dashboard?'+q);const r=await response.json();if(!response.ok)throw Error(r.error);render(r,stable===true);query=inputs();history.replaceState(null,'','?'+query);sessionStorage.setItem('predict-dashboard-query','?'+query);$('error').textContent=r.error||'';}catch(e){$('error').textContent='Could not load results. Use Refresh to try again. '+e.message;$('scan-state').textContent='Scan status is unavailable. Use Refresh to reconnect.';$('updated').textContent='';$('empty').hidden=true;$('product-coverage').replaceChildren();$('rows').replaceChildren();$('count').textContent='Results unavailable';$('mode').textContent='Connection or data unavailable';}finally{busy=false;if(pendingRefresh){pendingRefresh=false;refresh();}}}
for(const key of fields)$(key).onchange=refresh;
$('capture').onchange=()=>{followSession=null;refresh();};$('refresh').onclick=refresh;for(const v of ['arb','ev','research'])$(v).onclick=()=>{view=v;refresh();};
$('rows').onclick=e=>{const row=e.target.closest('tr');if(!row)return;sessionStorage.setItem('predict-selected-row',row.dataset.id);sessionStorage.setItem('predict-dashboard-query','?'+inputs());if(!e.target.closest('a,details'))location.href=row.querySelector('a').href;};
async function command(path){$('scan-state').textContent=path==='stop'?'Stopping feeds and saving observations…':'Starting scan…';if(path==='stop')$('mode').textContent='Stopping · observations frozen';$('start').disabled=true;$('stop').disabled=true;try{const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(path==='start'?{max_games:Number($('max-games').value),duration:Number($('duration').value)}:{})});const r=await response.json();if(!response.ok)throw Error(r.error);if(path==='start'){followSession=r.session;}await refresh();}catch(e){$('error').textContent='Could not '+path+' the scan. Use Refresh to check its status. '+e.message;}}
$('start').onclick=()=>command('start');$('stop').onclick=()=>command('stop');
// Status polling exists only while an explicitly started scan is active.
async function poll(){pollTimer=null;try{const s=await(await fetch('/api/status')).json();
 if(followSession){const r=await(await fetch('/api/dashboard')).json();if(r.captures.some(c=>c.id===followSession)){$('capture').innerHTML=r.captures.map(c=>`<option value="${esc(c.id)}">${esc(BoardView.captureLabel(c.label))}</option>`).join('');$('capture').value=followSession;query.set('capture',followSession);}}
 await refresh(true);
 if(s.active&&!pollTimer)pollTimer=setTimeout(poll,1500);else if(!s.active)followSession=null;
 }catch(e){$('error').textContent='Application unavailable. Use Refresh to reconnect.';}}
refresh();

if($('import-references'))$('import-references').onclick=async()=>{try{const file=$('reference-file').files[0];if(!file||file.size>1024*1024)throw Error('Choose a prepared reference JSON file under 1 MB');const response=await fetch('/api/references',{method:'POST',headers:{'Content-Type':'application/json'},body:await file.text()});const result=await response.json();if(!response.ok)throw Error(result.error);$('reference-import-status').textContent=result.imported+' references added to this scan.';await refresh();}catch(e){$('reference-import-status').textContent=e.message;}};

if($('import-resolutions'))$('import-resolutions').onclick=async()=>{try{const file=$('resolution-file').files[0];if(!file||file.size>1024*1024)throw Error('Choose a prepared resolution JSON file under 1 MB');const response=await fetch('/api/resolutions',{method:'POST',headers:{'Content-Type':'application/json'},body:await file.text()});const result=await response.json();if(!response.ok)throw Error(result.error);$('resolution-import-status').textContent=result.imported+' retained resolution records appended. Stop to inspect saved resolution history.';await refresh();}catch(e){$('resolution-import-status').textContent=e.message;}};
