'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let query=new URLSearchParams(location.search),view=query.get('view')||'arb',busy=false,pendingRefresh=false,last=null,pollTimer=null,followSession=null;
const fields=['quantity','scenario','sort','venue','freshness','search','positive'];
for(const key of fields)if(query.has(key)){if(key==='positive')$(key).checked=query.get(key)==='true';else $(key).value=query.get(key);}
function inputs(){const q=new URLSearchParams({view});for(const key of fields)q.set(key,key==='positive'?String($(key).checked):$(key).value);if($('capture').value)q.set('capture',$('capture').value);return q;}
function fmt(n,suffix=''){return n===null||n===undefined?'Unavailable':Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})+suffix;}
function link(r){const q=new URLSearchParams({session:r.session,hash:r.hash,cutoff:r.cutoff,quantity:$('quantity').value,scenario:$('scenario').value,candidate:r.candidate,view:view==='ev'?'ev':'arb'});q.set('contract',r.contract||r.legs[0].id);if(r.reference_id)q.set('reference',r.reference_id);if(view==='research')q.set('research','true');if(view==='ev'&&r.probability!=null){q.set('probability',r.probability);q.set('basis',r.assumption);}return '/game?'+q;}
function render(r,stable=false){const openRows=new Set([...document.querySelectorAll('#rows tr')].filter(x=>x.querySelector('details[open]')).map(x=>x.dataset.id));r.rows=r.rows.filter(x=>view!=='arb'||BoardView.crossVenue(x));if(stable&&last?.capture===r.capture){const order=new Map(last.rows.map((x,i)=>[x.id,i]));r.rows.sort((a,b)=>(order.get(a.id)??1e9)-(order.get(b.id)??1e9));}last=r;const s=r.status;if(s.active&&!pollTimer)pollTimer=setTimeout(poll,1500);$('max-games').disabled=s.active;$('max-games').parentElement.hidden=['d2-bounded-inventory','product-session'].includes(s.operating_mode);$('start').textContent=s.operating_mode==='d2-bounded-inventory'?'Coverage pilot':'Start scan';$('duration').disabled=s.active;$('start').disabled=!s.start_available;$('stop').disabled=!s.active;$('mode').textContent=!r.capture?'Idle · no session':r.state?((r.data_mode||'Saved')+' · '+r.state):r.live?'Current scan':(s.active?'Previous saved · not current':r.data_mode==='mock'?'Saved · local test':'Saved · real · not current');$('scan-state').textContent=s.active?'Scan '+s.state+' · order held until Refresh':(s.cleanup_errors?.length?'Cleanup failed · resource closure unconfirmed':s.start_available?'Idle · feeds stopped':s.state==='failed'?'Scan failed':'Idle · feeds stopped · verification allowance consumed');if(s.error)$('scan-state').textContent+=' · '+s.error;
 r.sources=r.sources||[...new Set(r.rows.flatMap(x=>x.venues||[]))].map(v=>({source_id:v,label:v,role:'prediction'}));const sourceChoice=$('venue').value;if(r.sources.length){$('venue').innerHTML='<option value="">All sources</option>'+r.sources.filter(x=>x.role==='prediction').map(x=>`<option value="${esc(x.source_id)}">${esc(x.label)}</option>`).join('');$('venue').value=sourceChoice;}
 const chosen=r.capture;$('capture').innerHTML=r.captures.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join('');$('capture').value=chosen||'';
 const c=r.coverage;$('coverage').textContent=c?`${c.selected} games · ${c.excluded.length} excluded · ${c.truncated_by_limit} beyond limit`:'Discovery pending';$('coverage-detail').textContent=JSON.stringify(c,null,2);$('product-coverage').innerHTML=r.market_catalog?'<p>'+r.sources.map(x=>esc(x.label)+(x.selected?' · selected':'')+' · '+esc(x.coverage?.state||x.state)+(x.environment?' · '+esc(x.environment):'')+(x.update_path?' · '+esc(x.update_path):'')).join(' | ')+'</p><details><summary>Markets and coverage gaps</summary>'+r.market_catalog.map(m=>'<p>'+esc(m.title)+' · '+esc(m.source_id)+' · '+esc(m.identity?.family)+' / '+esc(m.identity?.period)+' / '+esc(m.identity?.line??'no line')+' · '+esc(m.reason||(m.usable?'receiving':'awaiting usable book'))+(m.received_at?' · '+esc(m.update_path)+' · received '+esc(m.received_at):'')+(m.native?.display_prices||[]).map(p=>' · '+esc(p.label)+': displayed '+esc(p.available??'unavailable')+' / last trade '+esc(p.last??'unknown')+' (size unknown)').join('')+(m.quotes||[]).map(q=>' · '+esc(q.side)+': '+(q.ask==null?'ask unavailable':'$'+esc(q.ask))+' / '+(q.ask_size==null?'size unknown':esc(q.ask_size)+' '+esc(q.unit))).join('')+'</p>').join('')+'</details>':'';if(r.references?.length)$('product-coverage').innerHTML+='<details><summary>Retained references · '+r.references.length+'</summary>'+r.references.map(ref=>'<div class="retained-reference">'+esc(ref.provider_id)+' / '+esc(ref.origin_id)+' · '+esc(ref.market_identity?.competition)+' · '+esc(ref.participant)+' · '+esc(ref.value_kind)+' '+esc(ref.value)+'<br>'+esc(ref.market_identity?.family)+' / '+esc(ref.market_identity?.period)+' · '+esc(ref.reason||'Dated input; EV requires an exactly matching supported market')+'<br>As of '+esc(ref.source_at||'unknown')+' · received '+esc(ref.received_at)+'<br>'+esc(ref.dependency)+'<br>Scheduled '+esc(ref.market_identity?.scheduled_start)+' · delay '+esc(ref.delay_seconds??'unknown')+'<br>'+esc(ref.delay_basis)+'<details><summary>Original input and calculation basis</summary><p>'+esc(ref.conversion_method||'No probability conversion')+'</p><pre>'+esc(JSON.stringify(ref.original_value,null,2))+'</pre><p>Event '+esc(ref.source_event_id)+' · '+esc(ref.evidence_mode)+'<br>'+esc(ref.provenance)+'<br>Cutoff '+esc(r.durable_cursor)+'</p></details></div>').join('')+'</details>';$('updated').textContent='Captured '+(r.capture_time?new Date(r.capture_time).toLocaleString(undefined,{timeZoneName:'short'}):'—');$('last-observation').textContent='Last observation: '+(r.last_update||'—');
 $('arb').setAttribute('aria-pressed',view==='arb');$('ev').setAttribute('aria-pressed',view==='ev');$('research').setAttribute('aria-pressed',view==='research');for(const id of ['positive','venue','freshness'])$(id).disabled=view==='research';$('empty').textContent=r.live&&!r.rows.length&&!r.market_catalog?.some(m=>m.usable)?'Discovering markets and waiting for comparable books…':r.references?.length&&!r.market_catalog?.length?'References saved. EV unavailable: no compatible prediction observations in this session.':'No candidates match these filters.';$('explanation').textContent=view==='research'?'Retrospective, time-mismatched research · saved DraftKings probabilities and Kalshi YES asks. Conditional ordinary winners only; unconditional EV unavailable.':view==='arb'?'Conditional net: normal winners, modeled fees. Exceptional settlement and account fees unresolved.':'What-if EV · use a labeled dated reference or enter your own probability and basis in a game.';
 if(view==='research'){renderResearch(r);return;}
 $('head').innerHTML='<tr><th>Game</th><th>Buy / top price</th><th>Net $</th><th>Size</th><th></th></tr>';
 $('count').textContent=`${r.rows.length} ${view==='arb'?'cross-venue pairs':'what-if legs'} shown`;$('empty').hidden=r.rows.length>0;
 const selected=sessionStorage.getItem('predict-selected-row');$('rows').innerHTML=r.rows.map(x=>`<tr class="${x.usable?'':'unusable'} ${selected===x.id?'selected':''}" data-id="${esc(x.id)}"><td data-label="Game"><a href="${esc(link(x))}">${esc(x.game_title)}</a>${view==='ev'?'<small>'+esc(x.assumption)+'</small>':''}</td><td data-label="Buy / top price">${x.legs.map(l=>`<div>${esc(l.contract)}<small>${esc(l.label)} · ${l.ask==null?'Ask unavailable':'$'+esc(l.ask)}</small></div>`).join('')}</td><td data-label="Net $" class="number ${x.profit?.startsWith('-')?'negative':x.profit?'positive':''}">${esc(fmt(x.profit))}${x.profit!=null||x.status==='Assumption needed'?`<small>${esc(BoardView.status(x,x.profit))}</small>`:''}${BoardView.reasons(x).length?`<small class="warning">${esc(BoardView.reasons(x).join(' · '))}</small>`:''}</td><td data-label="Size">${esc(x.modeled_quantity)}<small>per leg${x.depth_limited?' · depth limited':''}</small></td><td data-label=""><details><summary>Details</summary><p>ROI ${esc(fmt(x.return_pct,'%'))}${view==='ev'?` · Break-even ${esc(fmt(x.break_even_pct,'%'))}`:''}</p><p>${esc(x.assumption)}${x.probability!=null?` · p=${esc(x.probability)}`:''}</p><p>Scheduled ${esc(new Date(x.start).toLocaleString())}<br>Cutoff ${esc(x.at)}<br>${x.usable?'Usable at cutoff':'Unavailable at cutoff'}</p>${(x.references||[]).map(r=>`<p>${esc(r.role)} · ${esc(r.provider_id)} / ${esc(r.origin_id)} · ${esc(r.value_kind)} ${esc(r.value)}<br>As of ${esc(r.model_as_of||r.source_at)} · Received ${esc(r.received_at)} · Delay ${esc(r.delay_seconds??'unknown')}<br>${esc(r.dependency||'Independence unknown')} · ${esc(r.freshness||'dated')}<br>${esc(r.reason||r.delay_basis||'')}<br>${esc(r.provenance)}</p>`).join('')}<a href="${esc(link(x))}">Game details →</a></details></td></tr>`).join('');
 for(const row of document.querySelectorAll('#rows tr'))if(openRows.has(row.dataset.id)){const detail=row.querySelector('details');if(detail)detail.open=true;}
}

function researchDetails(e){if(!e)return '';return `<p>Source retrieved ${esc(e.reference_retrieved_at)}<br>Target received ${esc(e.target_received_at)}<br>Original target cutoff ${esc(e.target_cutoff)}</p><p>DraftKings via <a href="${esc(e.source_url)}" target="_blank" rel="noreferrer">VegasInsider</a> · bookmaker update time and delay unknown.</p><p>${e.sides.map(s=>esc(s.team)+' '+esc(s.odds)).join(' / ')}</p><p>${esc(e.fee_basis)}</p><p>${esc(e.assessment.conclusion)}</p><p>${e.assessment.exceptional_differences.map(x=>esc(x.outcome)+': '+esc(x.draftkings)+' '+esc(x.kalshi)).join('<br>')}</p><pre>${esc(JSON.stringify({probability:e.probability,arithmetic:e.arithmetic,expected_payout:e.expected_payout,expected_profit:e.expected_profit,return_pct:e.return_pct,entry_cash:e.leg.cash,fee:e.leg.fee,binding:e.assessment.binding,limitations:e.limitations},null,2))}</pre>`;}
function renderResearch(r){
 $('head').innerHTML='<tr><th>Game / purchase</th><th>Page probability</th><th>Ask / size</th><th>Conditional net / ROI</th><th>Assumptions</th></tr>';
 $('count').textContent=`${r.rows.filter(x=>x.probability!=null).length} page-covered games · ${r.rows.length} shown`; $('empty').hidden=r.rows.length>0;
 const selected=sessionStorage.getItem('predict-selected-row');
 $('rows').innerHTML=r.rows.map(x=>`<tr class="${selected===x.id?'selected':''}" data-id="${esc(x.id)}"><td data-label="Game / purchase"><a href="${esc(link(x))}">${esc(x.game_title)}</a><small>Buy ${esc(x.target_team)} YES · Kalshi</small></td><td data-label="Page probability">${esc(x.research?x.research.sides.find(s=>s.team===x.target_team).percent+'%':x.probability??'Unavailable')}</td><td data-label="Ask / size">${x.legs[0]?.ask==null?'Unavailable':'$'+esc(x.legs[0].ask)}<small>${esc(x.requested_quantity)} requested / ${esc(x.available_size??'unknown')} available</small></td><td data-label="Conditional net / ROI" class="number ${x.profit?.startsWith('-')?'negative':x.profit==null||/^0(?:\.0+)?$/.test(x.profit)?'':'positive'}">${esc(x.profit==null?'Unavailable':'$'+x.research.display.expected_profit)}<small>${esc(x.return_pct==null?'ROI unavailable':x.research.display.return_pct+'% ROI')}</small></td><td data-label="Assumptions">${esc(x.assumption)}<details><summary>Details</summary>${researchDetails(x.research)}${x.source?`<pre>${esc(JSON.stringify(x.source,null,2))}</pre>`:''}${(x.references||[]).map(r=>`<p>${esc(r.role)} · ${esc(r.provider_id)} / ${esc(r.origin_id)} · ${esc(r.value_kind)} ${esc(r.value)}<br>As of ${esc(r.model_as_of||r.source_at)} · Received ${esc(r.received_at)} · Delay ${esc(r.delay_seconds??'unknown')}<br>${esc(r.dependency||'Independence unknown')} · ${esc(r.freshness||'dated')}<br>${esc(r.reason||r.delay_basis||'')}<br>${esc(r.provenance)}</p>`).join('')}<a href="${esc(link(x))}">Game details →</a></details></td></tr>`).join('');
}

async function refresh(stable=false){if(busy){if(stable!==true)pendingRefresh=true;return;}busy=true;try{const q=inputs();if(!q.has('capture')&&query.has('capture'))q.set('capture',query.get('capture'));q.set('assumptions',localStorage.getItem('predict-ev-assumptions')||'{}');const response=await fetch('/api/dashboard?'+q);const r=await response.json();if(!response.ok)throw Error(r.error);render(r,stable===true);query=inputs();history.replaceState(null,'','?'+query);sessionStorage.setItem('predict-dashboard-query','?'+query);$('error').textContent=r.error||'';}catch(e){$('error').textContent=e.message;$('rows').replaceChildren();$('count').textContent='Results unavailable';$('mode').textContent='Connection or data unavailable';}finally{busy=false;if(pendingRefresh){pendingRefresh=false;refresh();}}}
for(const key of fields)$(key).onchange=refresh;
$('capture').onchange=()=>{followSession=null;refresh();};$('refresh').onclick=refresh;for(const v of ['arb','ev','research'])$(v).onclick=()=>{view=v;refresh();};
$('rows').onclick=e=>{const row=e.target.closest('tr');if(!row)return;sessionStorage.setItem('predict-selected-row',row.dataset.id);sessionStorage.setItem('predict-dashboard-query','?'+inputs());if(!e.target.closest('a,details'))location.href=row.querySelector('a').href;};
async function command(path){$('scan-state').textContent=path==='stop'?'Stopping feeds and saving observations…':'Starting bounded discovery…';if(path==='stop')$('mode').textContent='Stopping · observations frozen';$('start').disabled=true;$('stop').disabled=true;try{const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(path==='start'?{max_games:Number($('max-games').value),duration:Number($('duration').value)}:{})});const r=await response.json();if(!response.ok)throw Error(r.error);if(path==='start'){followSession=r.session;}await refresh();}catch(e){$('error').textContent=e.message;}}
$('start').onclick=()=>command('start');$('stop').onclick=()=>command('stop');
// Status polling exists only while an explicitly started scan is active.
async function poll(){pollTimer=null;try{const s=await(await fetch('/api/status')).json();
 if(followSession){const r=await(await fetch('/api/dashboard')).json();if(r.captures.some(c=>c.id===followSession)){$('capture').innerHTML=r.captures.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join('');$('capture').value=followSession;query.set('capture',followSession);}}
 await refresh(true);
 if(s.active&&!pollTimer)pollTimer=setTimeout(poll,1500);else if(!s.active)followSession=null;
 }catch(e){$('error').textContent='Application unavailable. Use Refresh list to reconnect.';}}
refresh();

if($('import-references'))$('import-references').onclick=async()=>{try{const file=$('reference-file').files[0];if(!file||file.size>1024*1024)throw Error('Choose a prepared reference JSON file under 1 MB');const response=await fetch('/api/references',{method:'POST',headers:{'Content-Type':'application/json'},body:await file.text()});const result=await response.json();if(!response.ok)throw Error(result.error);await refresh();}catch(e){$('error').textContent=e.message;}};
