'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let query=new URLSearchParams(location.search),view=query.get('view')||'arb',busy=false,pendingRefresh=false,last=null,pollTimer=null,followSession=null;
const fields=['quantity','scenario','sort','venue','freshness','search','positive'];
for(const key of fields)if(query.has(key)){if(key==='positive')$(key).checked=query.get(key)==='true';else $(key).value=query.get(key);}
function inputs(){const q=new URLSearchParams({view});for(const key of fields)q.set(key,key==='positive'?String($(key).checked):$(key).value);if($('capture').value)q.set('capture',$('capture').value);return q;}
function fmt(n,suffix=''){return n===null||n===undefined?'Unavailable':Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})+suffix;}
function link(r){const q=new URLSearchParams({session:r.session,hash:r.hash,cutoff:r.cutoff,quantity:$('quantity').value,scenario:$('scenario').value,candidate:r.candidate,view:view==='ev'?'ev':'arb'});q.set('contract',r.contract||r.legs[0].id);if(view==='research')q.set('research','true');if(view==='ev'&&r.probability!=null){q.set('probability',r.probability);q.set('basis',r.assumption);}return '/game?'+q;}
function render(r,stable=false){r.rows=r.rows.filter(x=>view!=='arb'||BoardView.crossVenue(x));if(stable&&last?.capture===r.capture){const order=new Map(last.rows.map((x,i)=>[x.id,i]));r.rows.sort((a,b)=>(order.get(a.id)??1e9)-(order.get(b.id)??1e9));}last=r;const s=r.status;if(s.active&&!pollTimer)pollTimer=setTimeout(poll,1500);$('max-games').disabled=s.active;$('duration').disabled=s.active;$('start').disabled=!s.start_available;$('stop').disabled=!s.active;$('mode').textContent=r.live?'Current scan':(s.active?'Previous saved · not current':r.data_mode==='mock'?'Saved · local test':'Saved · real · not current');$('scan-state').textContent=s.active?'Scan '+s.state+' · order held until Refresh':(s.cleanup_errors?.length?'Cleanup failed · resource closure unconfirmed':s.start_available?'Idle · feeds stopped':s.state==='failed'?'Scan failed':'Idle · feeds stopped · verification allowance consumed');if(s.error)$('scan-state').textContent+=' · '+s.error;
 const chosen=r.capture;$('capture').innerHTML=r.captures.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join('');$('capture').value=chosen||'';
 const c=r.coverage;$('coverage').textContent=c?`${c.selected} games · ${c.excluded.length} excluded · ${c.truncated_by_limit} beyond limit`:'Discovery pending';$('coverage-detail').textContent=JSON.stringify(c,null,2);$('updated').textContent='Captured '+(r.capture_time?new Date(r.capture_time).toLocaleString(undefined,{timeZoneName:'short'}):'—');$('last-observation').textContent='Last observation: '+(r.last_update||'—');
 $('arb').setAttribute('aria-pressed',view==='arb');$('ev').setAttribute('aria-pressed',view==='ev');$('research').setAttribute('aria-pressed',view==='research');for(const id of ['positive','venue','freshness'])$(id).disabled=view==='research';$('explanation').textContent=view==='research'?'Retrospective, time-mismatched research · saved DraftKings probabilities and Kalshi YES asks. Conditional ordinary winners only; unconditional EV unavailable.':view==='arb'?'Conditional net: normal winners, modeled fees. Exceptional settlement and account fees unresolved.':'What-if EV · enter your own probability and basis in a game. No estimated fair probability.';
 if(view==='research'){renderResearch(r);return;}
 $('head').innerHTML='<tr><th>Game</th><th>Buy / top price</th><th>Net $</th><th>Size</th><th></th></tr>';
 $('count').textContent=`${r.rows.length} ${view==='arb'?'cross-venue pairs':'what-if legs'} shown`;$('empty').hidden=r.rows.length>0;
 const selected=sessionStorage.getItem('predict-selected-row');$('rows').innerHTML=r.rows.map(x=>`<tr class="${x.usable?'':'unusable'} ${selected===x.id?'selected':''}" data-id="${esc(x.id)}"><td data-label="Game"><a href="${esc(link(x))}">${esc(x.game_title)}</a></td><td data-label="Buy / top price">${x.legs.map(l=>`<div>${esc(l.contract)}<small>${esc(l.label)} · ${l.ask==null?'Ask unavailable':'$'+esc(l.ask)}</small></div>`).join('')}</td><td data-label="Net $" class="number ${x.profit?.startsWith('-')?'negative':x.profit?'positive':''}">${esc(fmt(x.profit))}${x.profit!=null||x.status==='Assumption needed'?`<small>${esc(BoardView.status(x,x.profit))}</small>`:''}${BoardView.reasons(x).length?`<small class="warning">${esc(BoardView.reasons(x).join(' · '))}</small>`:''}</td><td data-label="Size">${esc(x.modeled_quantity)}<small>per leg${x.depth_limited?' · depth limited':''}</small></td><td data-label=""><details><summary>Details</summary><p>ROI ${esc(fmt(x.return_pct,'%'))}${view==='ev'?` · Break-even ${esc(fmt(x.break_even_pct,'%'))}`:''}</p><p>${esc(x.assumption)}${x.probability!=null?` · p=${esc(x.probability)}`:''}</p><p>Scheduled ${esc(new Date(x.start).toLocaleString())}<br>Cutoff ${esc(x.at)}<br>${x.usable?'Usable at cutoff':'Unavailable at cutoff'}</p><a href="${esc(link(x))}">Game details →</a></details></td></tr>`).join('');
}

function researchDetails(e){if(!e)return '';return `<p>Source retrieved ${esc(e.reference_retrieved_at)}<br>Target received ${esc(e.target_received_at)}<br>Original target cutoff ${esc(e.target_cutoff)}</p><p>DraftKings via <a href="${esc(e.source_url)}" target="_blank" rel="noreferrer">VegasInsider</a> · bookmaker update time and delay unknown.</p><p>${e.sides.map(s=>esc(s.team)+' '+esc(s.odds)).join(' / ')}</p><p>${esc(e.fee_basis)}</p><p>${esc(e.assessment.conclusion)}</p><p>${e.assessment.exceptional_differences.map(x=>esc(x.outcome)+': '+esc(x.draftkings)+' '+esc(x.kalshi)).join('<br>')}</p><pre>${esc(JSON.stringify({probability:e.probability,arithmetic:e.arithmetic,expected_payout:e.expected_payout,expected_profit:e.expected_profit,return_pct:e.return_pct,entry_cash:e.leg.cash,fee:e.leg.fee,binding:e.assessment.binding,limitations:e.limitations},null,2))}</pre>`;}
function renderResearch(r){
 $('head').innerHTML='<tr><th>Game / purchase</th><th>Page probability</th><th>Ask / size</th><th>Conditional net / ROI</th><th>Assumptions</th></tr>';
 $('count').textContent=`${r.rows.filter(x=>x.probability!=null).length} page-covered games · ${r.rows.length} shown`; $('empty').hidden=r.rows.length>0;
 const selected=sessionStorage.getItem('predict-selected-row');
 $('rows').innerHTML=r.rows.map(x=>`<tr class="${selected===x.id?'selected':''}" data-id="${esc(x.id)}"><td data-label="Game / purchase"><a href="${esc(link(x))}">${esc(x.game_title)}</a><small>Buy ${esc(x.target_team)} YES · Kalshi</small></td><td data-label="Page probability">${esc(x.research?x.research.sides.find(s=>s.team===x.target_team).percent+'%':x.probability??'Unavailable')}</td><td data-label="Ask / size">${x.legs[0]?.ask==null?'Unavailable':'$'+esc(x.legs[0].ask)}<small>${esc(x.requested_quantity)} requested / ${esc(x.available_size??'unknown')} available</small></td><td data-label="Conditional net / ROI" class="number ${x.profit?.startsWith('-')?'negative':x.profit==null||/^0(?:\.0+)?$/.test(x.profit)?'':'positive'}">${esc(x.profit==null?'Unavailable':'$'+x.research.display.expected_profit)}<small>${esc(x.return_pct==null?'ROI unavailable':x.research.display.return_pct+'% ROI')}</small></td><td data-label="Assumptions">${esc(x.assumption)}<details><summary>Details</summary>${researchDetails(x.research)}${x.source?`<pre>${esc(JSON.stringify(x.source,null,2))}</pre>`:''}<a href="${esc(link(x))}">Game details →</a></details></td></tr>`).join('');
}

async function refresh(stable=false){if(busy){if(stable!==true)pendingRefresh=true;return;}busy=true;try{const q=inputs();if(!q.has('capture')&&query.has('capture'))q.set('capture',query.get('capture'));q.set('assumptions',localStorage.getItem('predict-ev-assumptions')||'{}');const response=await fetch('/api/dashboard?'+q);const r=await response.json();if(!response.ok)throw Error(r.error);render(r,stable===true);query=inputs();history.replaceState(null,'','?'+query);sessionStorage.setItem('predict-dashboard-query','?'+query);$('error').textContent='';}catch(e){$('error').textContent=e.message;$('rows').replaceChildren();$('count').textContent='Results unavailable';$('mode').textContent='Connection or data unavailable';}finally{busy=false;if(pendingRefresh){pendingRefresh=false;refresh();}}}
for(const key of fields)$(key).onchange=refresh;
$('capture').onchange=()=>{followSession=null;refresh();};$('refresh').onclick=refresh;for(const v of ['arb','ev','research'])$(v).onclick=()=>{view=v;refresh();};
$('rows').onclick=e=>{const row=e.target.closest('tr');if(!row)return;sessionStorage.setItem('predict-selected-row',row.dataset.id);sessionStorage.setItem('predict-dashboard-query','?'+inputs());if(!e.target.closest('a,details'))location.href=row.querySelector('a').href;};
async function command(path){$('scan-state').textContent=path==='stop'?'Stopping feeds and saving observations…':'Starting bounded discovery…';if(path==='stop')$('mode').textContent='Stopping · observations frozen';$('start').disabled=true;$('stop').disabled=true;try{const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(path==='start'?{max_games:Number($('max-games').value),duration:Number($('duration').value)}:{})});const r=await response.json();if(!response.ok)throw Error(r.error);if(path==='start'){followSession=r.session;}await refresh();}catch(e){$('error').textContent=e.message;}}
$('start').onclick=()=>command('start');$('stop').onclick=()=>command('stop');
// Status polling exists only while an explicitly started scan is active.
async function poll(){pollTimer=null;try{const s=await(await fetch('/api/status')).json();
 if(followSession){const r=await(await fetch('/api/dashboard')).json();if(r.captures.some(c=>c.id===followSession)){$('capture').innerHTML=r.captures.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join('');$('capture').value=followSession;query.set('capture',followSession);}}
 await refresh(true);
 if(s.active&&!pollTimer)pollTimer=setTimeout(poll,1500);else if(!s.active)followSession=null;
 }catch(e){$('error').textContent='Application unavailable. Use Refresh list to reconnect.';}}
refresh();
